import type { AdaptiveModuleDefinition } from "./adaptive-module-definition";

const interventions = {
  "m8-principe-standard-v1": {
    id: "m8-principe-standard-v1",
    objectiveId: "sa.m08.principe-onderscheiden",
    speaker: "alexander",
    title: "Een principe stuurt een afweging; een regel schrijft voor",
    kind: "explanation",
    body: "In deze module gebruiken we een principe als richtinggevende uitspraak waarmee je ontwerpkeuzes kunt beoordelen. Een regel of standaard schrijft veel directer voor wat wel of niet mag. Een principe dat alleen een ambitie noemt, zoals 'wij streven naar kwaliteit', helpt nauwelijks kiezen. Een bruikbaar principe maakt zichtbaar welke richting de voorkeur heeft en onder welke aantoonbare omstandigheden afwijking bespreekbaar is.",
    visualMode: "principle-rule-standard",
  },
  "m8-principe-practice-v1": {
    id: "m8-principe-practice-v1",
    objectiveId: "sa.m08.principe-beoordelen",
    speaker: "interviewer",
    title: "Kan dit principe werkelijk een ontwerp uitsluiten?",
    kind: "practice",
    body: "Middelveen gebruikt het principe: 'Wij werken toekomstvast.' Het klinkt positief, maar een reviewer kan er nauwelijks een concrete ontwerpkeuze mee toetsen.",
    prompt: "Wat ontbreekt aan deze formulering om er een bruikbaar architectuurprincipe van te maken?",
    visualMode: "principle-quality",
  },
  "m8-review-standard-v1": {
    id: "m8-review-standard-v1",
    objectiveId: "sa.m08.review-toetsen",
    speaker: "alexander",
    title: "Een review is een gesprek over onderbouwing",
    kind: "explanation",
    body: "Een architectuurreview is niet alleen een ja/nee-stempel. De reviewer maakt expliciet welke eis, welk principe of welke ontwerpregel relevant is, controleert hoe het ontwerp daarmee omgaat en vraagt naar de onderbouwing wanneer er spanning ontstaat. Een bezwaar als 'dit is niet hoe wij het doen' is te zwak zolang niet duidelijk is op welk toetsbaar kader het rust.",
    visualMode: "review-flow",
  },
  "m8-review-practice-v1": {
    id: "m8-review-practice-v1",
    objectiveId: "sa.m08.review-toetsen",
    speaker: "interviewer",
    title: "Toets de afwijking, niet de persoon",
    kind: "practice",
    body: "Het ontwerp slaat een keuringsuitslag lokaal op, terwijl een principe bronhouderschap als voorkeursrichting geeft. De ontwerper zegt dat directe bronbevraging operationeel onwerkbaar is.",
    prompt: "Welke eerste twee vragen stel je als reviewer voordat je goed- of afkeurt?",
    visualMode: "review-flow",
  },
  "m8-afwijking-standard-v1": {
    id: "m8-afwijking-standard-v1",
    objectiveId: "sa.m08.afwijking-beoordelen",
    speaker: "alexander",
    title: "Afwijken kan bewust en tijdelijk zijn",
    kind: "explanation",
    body: "Een principe is geen natuurwet. Een afwijking kan verdedigbaar zijn wanneer de reden expliciet is, de consequenties bekend zijn en duidelijk is onder welke termijn, voorwaarde of herbeoordelingsmoment de afwijking geldt. Vastleggen maakt zichtbaar dat de afwijking bewust is aangegaan en voorkomt dat een tijdelijke uitzondering ongemerkt de nieuwe standaard wordt.",
    visualMode: "deviation-record",
  },
  "m8-afwijking-practice-v1": {
    id: "m8-afwijking-practice-v1",
    objectiveId: "sa.m08.afwijking-beoordelen",
    speaker: "interviewer",
    title: "Wanneer is tijdelijk werkelijk tijdelijk?",
    kind: "practice",
    body: "Een project wil zes maanden lokaal kopiëren omdat de bronhouder nog geen betrouwbare interface heeft.",
    prompt: "Welke informatie moet in de afwijking staan zodat een latere reviewer kan bepalen of de uitzondering nog geldig is?",
    visualMode: "deviation-record",
  },
  "m8-verdedigen-practice-v1": {
    id: "m8-verdedigen-practice-v1",
    objectiveId: "sa.m08.review-toetsen",
    speaker: "interviewer",
    title: "Verdedig je ontwerp zonder in voorkeuren te vervallen",
    kind: "practice",
    body: "Je verwacht dat een reviewer bezwaar maakt tegen een nieuwe integratie omdat Middelveen normaal bestaande koppelingen hergebruikt.",
    prompt: "Hoe bouw je je verdediging op zodat het gesprek over principe, context en consequenties gaat in plaats van over persoonlijke voorkeur?",
    visualMode: "review-defense",
  },
  "m8-principe-verplichting-repair-v1": {
    id: "m8-principe-verplichting-repair-v1",
    objectiveId: "sa.m08.afwijking-beoordelen",
    speaker: "interviewer",
    title: "Herstel: een principe is niet automatisch een absoluut verbod",
    kind: "repair",
    body: "Wanneer ieder principe zonder uitzondering als harde regel wordt behandeld, verdwijnt de mogelijkheid om context en consequenties te wegen. De afwijking moet wel expliciet, onderbouwd en bestuurbaar zijn.",
    prompt: "Welke bewijslast hoort bij iemand die van een principe wil afwijken?",
    visualMode: "deviation-record",
  },
  "m8-stempel-repair-v1": {
    id: "m8-stempel-repair-v1",
    objectiveId: "sa.m08.review-toetsen",
    speaker: "interviewer",
    title: "Herstel: review is meer dan goedkeuren",
    kind: "repair",
    body: "Een review die alleen 'akkoord' of 'niet akkoord' oplevert, maakt de kwaliteit van de onderbouwing niet zichtbaar. De waarde zit in het expliciet toetsen van ontwerp, eisen, principes, consequenties en afwijkingen.",
    prompt: "Welke vraag maakt een review inhoudelijk toetsbaar in plaats van procedureel?",
    visualMode: "review-flow",
  },
  "m8-assessment-v1": {
    id: "m8-assessment-v1",
    objectiveId: "sa.m08.review-toetsen",
    speaker: "alexander",
    title: "Verplichte eindcheck",
    kind: "assessment",
    body: "De eindcheck controleert of je principes van regels onderscheidt, bruikbaarheid beoordeelt, een ontwerp aan een gegeven kader toetst en een afwijking inhoudelijk kunt beoordelen en vastleggen.",
    visualMode: "assessment",
  },
} as const;

export const solutionArchitectureModule8: AdaptiveModuleDefinition = {
  courseSlug: "solution-architectuur-ontwerppraktijk",
  sourceModuleId: 8,
  moduleSlug: "principes-governance-en-review",
  title: "Principes, governance en review",
  // De canonieke bron waarschuwt om NORA/GEMMA niet te introduceren zonder actuele verificatie.
  // Deze module blijft daarom bewust generiek en toetst geen externe overheidsreferentiearchitectuur.
  standardReferences: [],
  objectives: [
    "sa.m08.principe-onderscheiden",
    "sa.m08.principe-beoordelen",
    "sa.m08.review-toetsen",
    "sa.m08.afwijking-beoordelen",
  ],
  misconceptions: [
    "sa.mc.principe-is-absolute-verplichting",
    "sa.mc.review-is-goedkeuringsstempel",
  ],
  diagnostics: [
    {
      id: "m8-diag-01",
      objectiveIds: ["sa.m08.principe-onderscheiden"],
      prompt: "Wat onderscheidt een architectuurprincipe in deze module het best van een harde regel?",
      kind: "single_choice",
      options: ["Een principe is vrijblijvend", "Een principe geeft richting bij afwegingen; een regel schrijft een uitkomst voor", "Een principe is altijd technischer", "Er is geen verschil"],
    },
    {
      id: "m8-diag-02",
      objectiveIds: ["sa.m08.principe-beoordelen"],
      prompt: "Welk principe helpt een reviewer daadwerkelijk kiezen?",
      kind: "single_choice",
      options: ["Wij zijn innovatief", "Gegevens worden opgeslagen bij de bronhouder, tenzij aantoonbaar onwerkbaar", "Wij streven naar kwaliteit", "Wij werken toekomstvast"],
    },
    {
      id: "m8-diag-03",
      objectiveIds: ["sa.m08.review-toetsen"],
      prompt: "Een reviewer zegt alleen: 'dit is niet hoe wij het doen.' Wat is het grootste probleem?",
      kind: "single_choice",
      options: ["De toon is te streng", "Het bezwaar is niet gekoppeld aan een principe, eis of ander toetsbaar kader", "De reviewer geeft geen alternatief", "Er ontbreekt een handtekening"],
    },
    {
      id: "m8-diag-04",
      objectiveIds: ["sa.m08.afwijking-beoordelen"],
      prompt: "Een ontwerp wijkt aantoonbaar af van een principe. Wat is de beste eerste reactie?",
      kind: "single_choice",
      options: ["Automatisch afkeuren", "Onderbouwing, consequenties en voorwaarden van de afwijking beoordelen en vastleggen", "Het principe meteen aanpassen", "Goedkeuren omdat principes alleen richting geven"],
    },
  ],
  interventions,
  routes: {
    A: [
      "m8-principe-standard-v1",
      "m8-principe-practice-v1",
      "m8-review-standard-v1",
      "m8-review-practice-v1",
      "m8-afwijking-standard-v1",
      "m8-afwijking-practice-v1",
      "m8-verdedigen-practice-v1",
      "m8-assessment-v1",
    ],
    B: [
      "m8-principe-practice-v1",
      "m8-review-practice-v1",
      "m8-afwijking-practice-v1",
      "m8-verdedigen-practice-v1",
      "m8-assessment-v1",
    ],
    C: [
      "m8-principe-verplichting-repair-v1",
      "m8-stempel-repair-v1",
      "m8-review-practice-v1",
      "m8-afwijking-practice-v1",
      "m8-assessment-v1",
    ],
  },
  assessment: [
    {
      id: "m8-assess-01",
      objectiveId: "sa.m08.principe-onderscheiden",
      question: "Wat onderscheidt een principe van een regel?",
      options: ["Een principe is vrijblijvend", "Een principe geeft richting bij afwegingen; een regel schrijft een uitkomst voor", "Een principe is technischer", "Er is geen verschil"],
    },
    {
      id: "m8-assess-02",
      objectiveId: "sa.m08.principe-beoordelen",
      question: "Welk principe is bruikbaar bij het maken van keuzes?",
      options: ["Wij streven naar kwaliteit", "Gegevens worden opgeslagen bij de bronhouder, tenzij aantoonbaar onwerkbaar", "Wij zijn innovatief", "Wij werken toekomstvast"],
    },
    {
      id: "m8-assess-03",
      objectiveId: "sa.m08.review-toetsen",
      question: "Een ontwerp slaat de keuringsuitslag in het zaaksysteem op, terwijl het principe bronhouderschap voorschrijft. Wat is de juiste reactie in een review?",
      options: ["Afkeuren", "Goedkeuren, principes zijn richtinggevend", "Vragen om de onderbouwing van de afwijking en die als afwijking vastleggen", "Het principe aanpassen"],
    },
    {
      id: "m8-assess-04",
      objectiveId: "sa.m08.afwijking-beoordelen",
      question: "Wat maakt een afwijking verdedigbaar?",
      options: ["Dat de opdrachtgever ermee instemt", "Dat de consequenties benoemd zijn en er een termijn of voorwaarde aan hangt", "Dat het sneller is", "Dat niemand bezwaar maakt"],
    },
    {
      id: "m8-assess-05",
      objectiveId: "sa.m08.review-toetsen",
      question: "Een reviewer zegt: 'dit is niet hoe wij het doen.' Wat ontbreekt aan dit bezwaar?",
      options: ["Niets, het is duidelijk", "Een principe of eis waarop het bezwaar steunt, dus het is niet weerlegbaar", "Een alternatief", "Een handtekening"],
    },
    {
      id: "m8-assess-06",
      objectiveId: "sa.m08.afwijking-beoordelen",
      question: "Waarvoor dient het vastleggen van afwijkingen?",
      options: ["Voor de accountant", "Zodat later zichtbaar is dat de afwijking bewust is aangegaan en onder welke voorwaarde", "Om de architect te beschermen", "Om het principe te kunnen schrappen"],
    },
  ],
  mediaPolicy: { interviewerVideo: false, optionalTutorClipIds: [] },
};
