import type { AdaptiveModuleDefinition } from "./adaptive-module-definition";

const interventions = {
  "m1-rollen-standard-v1": {
    id: "m1-rollen-standard-v1",
    objectiveId: "sa.m01.rollen-onderscheiden",
    speaker: "alexander",
    title: "Vier architectuurrollen, vier verschillende vragen",
    kind: "explanation",
    body: "In deze cursus gebruiken we vier rollen als werkmodel. Business-architectuur richt zich op de inrichting van de dienstverlening en het businessvermogen. Enterprise-architectuur bewaakt samenhang en richting over het bredere landschap. Solution-architectuur vertaalt een concrete veranderopgave naar een samenhangende oplossing over systemen en interfaces heen. Software-architectuur zoomt verder in op de interne softwarestructuur. Organisaties kunnen andere functietitels gebruiken; de grens wordt bepaald door het type beslissing, niet door het visitekaartje.",
    visualMode: "role-map",
  },
  "m1-solution-mandaat-standard-v1": {
    id: "m1-solution-mandaat-standard-v1",
    objectiveId: "sa.m01.mandaat",
    speaker: "alexander",
    title: "Ontwerp de oplossing, niet de dienstverlening zelf",
    kind: "explanation",
    body: "De solution architect neemt ontwerpbeslissingen die de oplossing als geheel raken: systeemgrenzen, gegevensuitwisseling, afhankelijkheden en de consequenties van keuzes. Een beslissing om een dienst wel of niet aan te bieden, of om een papieren kanaal af te schaffen, hoort niet automatisch bij dit mandaat. Andersom is een lokaal teamdetail zonder bredere impact meestal geen solution-architectuurbeslissing.",
    visualMode: "decision-boundary",
  },
  "m1-mandaat-invloed-practice-v1": {
    id: "m1-mandaat-invloed-practice-v1",
    objectiveId: "sa.m01.mandaat-invloed",
    speaker: "interviewer",
    title: "Mandaat is niet hetzelfde als invloed",
    kind: "practice",
    body: "De enterprise architect heeft bepaald dat Middelveen een landelijke voorziening moet gebruiken. Jij kunt die keuze niet zelfstandig terugdraaien, maar je bent ook niet klaar met alleen 'akkoord'.",
    prompt: "Wat kun jij als solution architect nog wél beïnvloeden, en wat leg je terug als de consequenties onaanvaardbaar zijn?",
    visualMode: "mandate-influence",
  },
  "m1-conflict-standard-v1": {
    id: "m1-conflict-standard-v1",
    objectiveId: "sa.m01.belangen-analyseren",
    speaker: "alexander",
    title: "Rollen botsen vaak op tijdshorizon, niet op gelijk",
    kind: "explanation",
    body: "Een opdrachtgever kan sturen op snel projectresultaat terwijl enterprise-architectuur stuurt op landschapskwaliteit en lange termijn. De solution architect maakt die spanning concreet voor de oplossing: wat levert snelheid nu op, welke schuld of afhankelijkheid ontstaat later, en welke keuze moet door de bevoegde rol worden genomen?",
    visualMode: "role-conflict",
  },
  "m1-conflict-practice-v1": {
    id: "m1-conflict-practice-v1",
    objectiveId: "sa.m01.belangen-analyseren",
    speaker: "interviewer",
    title: "Projecttempo versus landschapskwaliteit",
    kind: "practice",
    body: "De opdrachtgever wil binnen drie maanden live. De enterprise architect wil eerst het landschap saneren.",
    prompt: "Benoem het onderliggende belangenconflict zonder één van beide rollen direct gelijk te geven. Welke consequenties moet jij zichtbaar maken?",
    visualMode: "role-conflict",
  },
  "m1-businessvraag-repair-v1": {
    id: "m1-businessvraag-repair-v1",
    objectiveId: "sa.m01.rollen-onderscheiden",
    speaker: "interviewer",
    title: "Herstel: niet iedere veranderkeuze is een solutionkeuze",
    kind: "repair",
    body: "Wanneer Middelveen besluit of burgers überhaupt digitaal moeten kunnen aanvragen, gaat het eerst over de dienstverlening. De solution architect kan consequenties en haalbaarheid inbrengen, maar eigent zich de businesskeuze niet toe.",
    prompt: "Welke vraag zou jij terugleggen voordat je een solutionontwerp maakt?",
    visualMode: "decision-boundary",
  },
  "m1-invloed-repair-v1": {
    id: "m1-invloed-repair-v1",
    objectiveId: "sa.m01.mandaat-invloed",
    speaker: "interviewer",
    title: "Herstel: geen formeel mandaat betekent niet geen invloed",
    kind: "repair",
    body: "Architectuurwerk is niet alleen formele beslissingsmacht. Ook wanneer een keuze elders ligt, kun je gevolgen onderzoeken, alternatieven onderbouwen, risico's expliciteren en een knelpunt terugleggen bij de eigenaar van de beslissing.",
    prompt: "Welke invloed blijft over wanneer jij de formele keuze niet mag nemen?",
    visualMode: "mandate-influence",
  },
  "m1-assessment-v1": {
    id: "m1-assessment-v1",
    objectiveId: "sa.m01.rollen-onderscheiden",
    speaker: "alexander",
    title: "Verplichte eindcheck",
    kind: "assessment",
    body: "De eindcheck controleert of je rolgrenzen, solutionmandaat, invloed en conflicterende belangen in concrete situaties herkent. Functietitels kunnen per organisatie verschillen; de toets gaat om de aard van de beslissing.",
    visualMode: "assessment",
  },
} as const;

export const solutionArchitectureModule1: AdaptiveModuleDefinition = {
  courseSlug: "solution-architectuur-ontwerppraktijk",
  sourceModuleId: 1,
  moduleSlug: "rol-en-positionering",
  title: "Rol en positionering",
  standardReferences: [],
  objectives: [
    "sa.m01.rollen-onderscheiden",
    "sa.m01.mandaat",
    "sa.m01.mandaat-invloed",
    "sa.m01.belangen-analyseren",
  ],
  misconceptions: [
    "sa.mc.solution-architect-gaat-over-businessvraag",
    "sa.mc.mandaat-is-invloed",
  ],
  diagnostics: [
    {
      id: "m1-diag-01",
      objectiveIds: ["sa.m01.rollen-onderscheiden"],
      prompt: "Wie hoort primair te besluiten of Middelveen de papieren aanvraag als dienstverleningskanaal afschaft?",
      kind: "single_choice",
      options: ["Business-architect / businessverantwoordelijke", "Solution architect", "Software-architect", "Ontwikkelteam"],
    },
    {
      id: "m1-diag-02",
      objectiveIds: ["sa.m01.mandaat"],
      prompt: "Een ontwikkelteam vraagt welk testframework het moet gebruiken en de keuze raakt geen andere systemen. Wat doe je?",
      kind: "single_choice",
      options: ["Ik kies het framework als solution architect", "Ik laat dit bij het team zolang er geen bredere architectuurimpact is", "Ik escalereer altijd naar enterprise-architectuur", "Ik blokkeer de bouw tot er een ADR is"],
    },
    {
      id: "m1-diag-03",
      objectiveIds: ["sa.m01.mandaat-invloed"],
      prompt: "Enterprise-architectuur schrijft een landelijke voorziening voor. Welke uitspraak past het best bij jouw rol?",
      kind: "single_choice",
      options: ["Ik heb niets meer te beïnvloeden", "Ik kan de keuze zelfstandig overrulen", "Ik werk de consequenties uit en leg onaanvaardbare knelpunten terug", "Ik negeer het kader als mijn ontwerp beter is"],
    },
    {
      id: "m1-diag-04",
      objectiveIds: ["sa.m01.belangen-analyseren"],
      prompt: "De opdrachtgever wil snel live; enterprise-architectuur wil eerst het landschap saneren. Wat botst hier vooral?",
      kind: "single_choice",
      options: ["Persoonlijke voorkeur", "Projectresultaat op korte termijn versus landschapskwaliteit op langere termijn", "Alleen budget", "Alleen technische kennis"],
    },
  ],
  interventions,
  routes: {
    A: [
      "m1-rollen-standard-v1",
      "m1-solution-mandaat-standard-v1",
      "m1-mandaat-invloed-practice-v1",
      "m1-conflict-standard-v1",
      "m1-conflict-practice-v1",
      "m1-assessment-v1",
    ],
    B: [
      "m1-solution-mandaat-standard-v1",
      "m1-mandaat-invloed-practice-v1",
      "m1-conflict-practice-v1",
      "m1-assessment-v1",
    ],
    C: [
      "m1-businessvraag-repair-v1",
      "m1-invloed-repair-v1",
      "m1-conflict-practice-v1",
      "m1-assessment-v1",
    ],
  },
  assessment: [
    {
      id: "m1-assess-01",
      objectiveId: "sa.m01.rollen-onderscheiden",
      question: "Wie bepaalt primair of de gemeente überhaupt digitaal wil aanvragen?",
      options: ["Business-architect / businessverantwoordelijke", "Solution architect", "Software-architect", "Enterprise architect"],
    },
    {
      id: "m1-assess-02",
      objectiveId: "sa.m01.mandaat",
      question: "Wat valt buiten het mandaat van de solution architect bij Middelveen?",
      options: ["Kiezen hoe de keuringsuitslag wordt uitgewisseld", "Bepalen hoe het zaaksysteem in de oplossing wordt gebruikt", "Besluiten dat de gemeente stopt met de papieren aanvraag", "Vaststellen welke gegevens de oplossing uit de BRP nodig heeft"],
    },
    {
      id: "m1-assess-03",
      objectiveId: "sa.m01.mandaat",
      question: "Een ontwikkelteam vraagt welk testframework het moet gebruiken en de keuze raakt geen ander systeem. Wat doe je?",
      options: ["Kiezen en vastleggen in een ADR", "Teruggeven aan het team", "Escaleren naar de enterprise architect", "Verbieden tot er beleid is"],
    },
    {
      id: "m1-assess-04",
      objectiveId: "sa.m01.mandaat-invloed",
      question: "De enterprise architect wijst een landelijke voorziening aan die Middelveen moet gebruiken. Wat is jouw rol?",
      options: ["De keuze overrulen als hij niet past", "De consequenties voor deze oplossing uitwerken en knelpunten terugleggen", "De keuze negeren en zelf ontwerpen", "Wachten tot het beleid verandert"],
    },
    {
      id: "m1-assess-05",
      objectiveId: "sa.m01.belangen-analyseren",
      question: "De opdrachtgever wil binnen drie maanden live; de enterprise architect wil eerst het landschap saneren. Wat is de kern van het conflict?",
      options: ["Persoonlijke voorkeuren", "Verschillende tijdshorizonnen: projectresultaat versus landschapskwaliteit", "Onduidelijke rolverdeling", "Onvoldoende budget"],
    },
    {
      id: "m1-assess-06",
      objectiveId: "sa.m01.belangen-analyseren",
      question: "Waaraan herken je dat een solution architect te laat is aangeschoven?",
      options: ["Er is nog geen ADR geschreven", "Een keuze die het landschap raakt ligt al in code vast", "Het project loopt uit", "De opdrachtgever stelt veel vragen"],
    },
  ],
  mediaPolicy: {
    interviewerVideo: false,
    optionalTutorClipIds: [],
  },
};
