import type { AdaptiveModuleDefinition } from "./adaptive-module-definition";

const interventions = {
  "m4-kwaliteit-vs-functie-standard-v1": {
    id: "m4-kwaliteit-vs-functie-standard-v1",
    objectiveId: "sa.m04.attributen-herkennen",
    speaker: "alexander",
    title: "Wat versus hoe goed",
    kind: "explanation",
    body: "Een functionele eis beschrijft wat de oplossing moet doen. Een kwaliteitsattribuut beschrijft hoe goed de oplossing dat moet doen of welke kwaliteit de oplossing daarbij moet bezitten. 'De burger kan status bekijken' is functioneel; '95% van de statuspagina's opent binnen 2 seconden bij 2.000 gelijktijdige gebruikers' beschrijft kwaliteit.",
    visualMode: "quality-vs-function",
  },
  "m4-iso25010-standard-v1": {
    id: "m4-iso25010-standard-v1",
    objectiveId: "sa.m04.attributen-herkennen",
    speaker: "alexander",
    title: "ISO/IEC 25010:2023 als begrippenkaart",
    kind: "explanation",
    body: "ISO/IEC 25010:2023 geeft een productkwaliteitsmodel met negen hoofdkenmerken: functional suitability, performance efficiency, compatibility, interaction capability, reliability, security, maintainability, flexibility en safety. In deze module gebruik je het model vooral als begrippenkaart: om eisen te classificeren, hiaten te herkennen en preciezer te formuleren. Je hoeft niet elk subkenmerk uit het hoofd te leren.",
    visualMode: "iso25010-map",
  },
  "m4-meetbaar-standard-v1": {
    id: "m4-meetbaar-standard-v1",
    objectiveId: "sa.m04.meetbaar-maken",
    speaker: "alexander",
    title: "Een bijvoeglijk naamwoord is nog geen eis",
    kind: "explanation",
    body: "Snel, veilig, betrouwbaar en beschikbaar zijn richtingwoorden. Voor ontwerp en toetsing heb je minimaal context, een meetbare maat en een norm nodig. 'Beschikbaar' wordt bijvoorbeeld bruikbaar als je benoemt wanneer je meet, wat als beschikbaar telt en welke grens acceptabel is.",
    visualMode: "quality-scenario-builder",
  },
  "m4-meetbaar-practice-v1": {
    id: "m4-meetbaar-practice-v1",
    objectiveId: "sa.m04.meetbaar-maken",
    speaker: "interviewer",
    title: "Maak 'snel' toetsbaar",
    kind: "practice",
    body: "Middelveen zegt: 'Het burgerportaal moet snel zijn.' Eva wil weten of je van dat woord een bruikbare architectuureis kunt maken.",
    prompt: "Formuleer één meetbare performance-eis. Noem ten minste wat je meet, een grenswaarde en de omstandigheden waaronder die norm geldt.",
    visualMode: "quality-scenario-builder",
  },
  "m4-spanning-standard-v1": {
    id: "m4-spanning-standard-v1",
    objectiveId: "sa.m04.spanning-analyseren",
    speaker: "alexander",
    title: "Kwaliteit kun je niet overal tegelijk maximaliseren",
    kind: "explanation",
    body: "Kwaliteitsattributen kunnen elkaar in een concreet ontwerp beïnvloeden. Een langere sessie kan de interactie eenvoudiger maken, maar het beveiligingsrisico vergroten. Extra redundantie kan beschikbaarheid verhogen, maar kosten en beheercomplexiteit vergroten. De architect maakt die spanning expliciet; Module 6 gaat daarna over het kiezen tussen serieuze alternatieven.",
    visualMode: "quality-tension",
  },
  "m4-tension-practice-v1": {
    id: "m4-tension-practice-v1",
    objectiveId: "sa.m04.spanning-analyseren",
    speaker: "interviewer",
    title: "Benoem winst én verlies",
    kind: "practice",
    body: "Middelveen overweegt een zeer lange inlogsessie zodat burgers minder vaak opnieuw hoeven in te loggen.",
    prompt: "Welk kwaliteitsattribuut kan hiervan profiteren, welk attribuut kan eronder lijden, en waarom?",
    visualMode: "quality-tension",
  },
  "m4-prioriteren-standard-v1": {
    id: "m4-prioriteren-standard-v1",
    objectiveId: "sa.m04.context-prioriteren",
    speaker: "alexander",
    title: "Niet alles is hier even bepalend",
    kind: "explanation",
    body: "Een referentiemodel helpt je niets vergeten, maar de context bepaalt welke kwaliteitskenmerken het ontwerp werkelijk sturen. Voor Middelveen kunnen vertrouwelijkheid, beschikbaarheid, performance en onderhoudbaarheid relevant zijn, maar hun gewicht volgt uit de dienstverlening, stakeholders, risico's en randvoorwaarden — niet uit de volgorde van een standaard.",
    visualMode: "quality-priority",
  },
  "m4-prioriteit-practice-v1": {
    id: "m4-prioriteit-practice-v1",
    objectiveId: "sa.m04.context-prioriteren",
    speaker: "interviewer",
    title: "Kies de drie die het ontwerp sturen",
    kind: "practice",
    body: "De fictieve Middelveen-casus bevat gevoelige keuringsgegevens, online statusinzage en koppelingen met bestaande systemen.",
    prompt: "Welke drie kwaliteitskenmerken zou jij als eerste expliciet maken en waarom juist deze drie?",
    visualMode: "quality-priority",
  },
  "m4-adjectief-repair-v1": {
    id: "m4-adjectief-repair-v1",
    objectiveId: "sa.m04.meetbaar-maken",
    speaker: "interviewer",
    title: "Herstel: 'betrouwbaar' is nog niet toetsbaar",
    kind: "repair",
    body: "Een eigenschap benoemen is nuttig voor het gesprek, maar nog onvoldoende voor ontwerp en acceptatie. Je moet kunnen vaststellen wanneer je aan de eis voldoet.",
    prompt: "Welke informatie ontbreekt nog aan 'het systeem moet betrouwbaar zijn' voordat je deze eis kunt toetsen?",
    visualMode: "quality-scenario-builder",
  },
  "m4-maximaliseren-repair-v1": {
    id: "m4-maximaliseren-repair-v1",
    objectiveId: "sa.m04.spanning-analyseren",
    speaker: "interviewer",
    title: "Herstel: overal maximaal is geen ontwerpstrategie",
    kind: "repair",
    body: "Als elk kwaliteitskenmerk zonder context maximale prioriteit krijgt, heb je geen bruikbare ontwerpsturing. Ontwerpen betekent grenzen, prioriteiten en spanningen expliciet maken.",
    prompt: "Waarom is 'alle kwaliteitsattributen krijgen prioriteit 1' geen bruikbare architectuurrichting?",
    visualMode: "quality-priority",
  },
  "m4-assessment-v1": {
    id: "m4-assessment-v1",
    objectiveId: "sa.m04.meetbaar-maken",
    speaker: "alexander",
    title: "Verplichte eindcheck",
    kind: "assessment",
    body: "De eindcheck controleert of je kwaliteitsattributen kunt herkennen, meetbaar maken, contextualiseren en spanning ertussen kunt analyseren. De beoordeling gebeurt server-side volgens vaste regels.",
    visualMode: "assessment",
  },
} as const;

export const solutionArchitectureModule4: AdaptiveModuleDefinition = {
  courseSlug: "solution-architectuur-ontwerppraktijk",
  sourceModuleId: 4,
  moduleSlug: "kwaliteitsattributen",
  title: "Kwaliteitsattributen",
  standardReferences: [
    {
      name: "ISO/IEC 25010",
      version: "2023",
      reference: "ISO/IEC 25010:2023, Edition 2, November 2023 — Product quality model",
    },
  ],
  objectives: [
    "sa.m04.attributen-herkennen",
    "sa.m04.meetbaar-maken",
    "sa.m04.spanning-analyseren",
    "sa.m04.context-prioriteren",
  ],
  misconceptions: [
    "sa.mc.kwaliteitsattribuut-is-oplossing",
    "sa.mc.bijvoeglijk-naamwoord-is-eis",
    "sa.mc.getal-zonder-context-is-toetsbaar",
    "sa.mc.alle-attributen-maximaliseren",
  ],
  diagnostics: [
    {
      id: "m4-diag-01",
      objectiveIds: ["sa.m04.attributen-herkennen"],
      prompt: "Middelveen eist dat alleen bevoegde medewerkers de keuringsgegevens kunnen inzien. Welk kwaliteitsgebied staat hier primair centraal?",
      kind: "single_choice",
      options: ["Performance efficiency", "Security / confidentiality", "Maintainability", "Functional suitability"],
    },
    {
      id: "m4-diag-02",
      objectiveIds: ["sa.m04.meetbaar-maken"],
      prompt: "De eis luidt: 'Het portaal moet betrouwbaar zijn.' Wat ontbreekt vooral om deze eis toetsbaar te maken?",
      kind: "single_choice",
      options: ["Een technisch ontwerp", "Een norm, meetwijze en relevante omstandigheden", "Een leverancier", "Een architectuurdiagram"],
    },
    {
      id: "m4-diag-03",
      objectiveIds: ["sa.m04.meetbaar-maken"],
      prompt: "Maak de wens 'de statuspagina moet snel zijn' in één zin meetbaar.",
      kind: "free_text",
    },
    {
      id: "m4-diag-04",
      objectiveIds: ["sa.m04.spanning-analyseren"],
      prompt: "Een langere inlogsessie geeft burgers minder onderbrekingen, maar vergroot de periode waarin misbruik mogelijk is. Wat zie je hier?",
      kind: "single_choice",
      options: ["Alleen een securityprobleem", "Alleen een usabilityprobleem", "Een spanning tussen interaction capability en security", "Geen kwaliteitsvraag maar alleen techniek"],
    },
  ],
  interventions,
  routes: {
    A: [
      "m4-kwaliteit-vs-functie-standard-v1",
      "m4-iso25010-standard-v1",
      "m4-meetbaar-standard-v1",
      "m4-meetbaar-practice-v1",
      "m4-spanning-standard-v1",
      "m4-tension-practice-v1",
      "m4-prioriteren-standard-v1",
      "m4-prioriteit-practice-v1",
      "m4-assessment-v1",
    ],
    B: [
      "m4-iso25010-standard-v1",
      "m4-meetbaar-practice-v1",
      "m4-tension-practice-v1",
      "m4-prioriteit-practice-v1",
      "m4-assessment-v1",
    ],
    C: [
      "m4-adjectief-repair-v1",
      "m4-maximaliseren-repair-v1",
      "m4-iso25010-standard-v1",
      "m4-tension-practice-v1",
      "m4-prioriteit-practice-v1",
      "m4-assessment-v1",
    ],
  },
  assessment: [
    {
      id: "m4-assess-01",
      objectiveId: "sa.m04.attributen-herkennen",
      question: "Welke formulering beschrijft primair een kwaliteitskenmerk en niet alleen functionaliteit?",
      options: ["De burger kan de aanvraag indienen", "95% van de statuspagina's opent binnen 2 seconden bij 2.000 gelijktijdige gebruikers", "De behandelaar kan een besluit registreren", "De keuringsinstantie stuurt een uitslag"],
    },
    {
      id: "m4-assess-02",
      objectiveId: "sa.m04.meetbaar-maken",
      question: "Welke beschikbaarheidseis is het best toetsbaar?",
      options: ["Het portaal is vrijwel altijd beschikbaar", "Het portaal heeft hoge beschikbaarheid", "Tijdens de afgesproken dienstperiode is het portaal per kalendermaand minimaal 99,9% beschikbaar, volgens de centrale beschikbaarheidsmeting", "Uitval moet zo veel mogelijk worden voorkomen"],
    },
    {
      id: "m4-assess-03",
      objectiveId: "sa.m04.attributen-herkennen",
      question: "Waarvoor gebruik je ISO/IEC 25010:2023 in deze module vooral?",
      options: ["Om voor elk kenmerk automatisch prioriteit 1 te eisen", "Als referentiemodel om kwaliteitseigenschappen te classificeren en eisen op volledigheid te onderzoeken", "Om een technisch ontwerp voor te schrijven", "Om alleen softwarecode te beoordelen"],
    },
    {
      id: "m4-assess-04",
      objectiveId: "sa.m04.spanning-analyseren",
      question: "Wat is de beste beschrijving van de lange-inlogsessie uit de casus?",
      options: ["Een fout ontwerp omdat security altijd voorrang heeft", "Een functionele eis", "Een mogelijke trade-off tussen interaction capability en security die expliciete grenzen vraagt", "Geen architectuuronderwerp"],
    },
    {
      id: "m4-assess-05",
      objectiveId: "sa.m04.context-prioriteren",
      question: "Hoe bepaal je welke kwaliteitskenmerken het ontwerp van Middelveen vooral sturen?",
      options: ["Alle negen krijgen dezelfde hoogste prioriteit", "De architect kiest zijn persoonlijke top drie", "Je gebruikt alleen de kenmerken die een leverancier al ondersteunt", "Je relateert kwaliteitskenmerken aan context, stakeholders, risico's en doelen en maakt prioriteiten expliciet"],
    },
  ],
  mediaPolicy: {
    interviewerVideo: false,
    optionalTutorClipIds: ["m4-kwaliteit-vs-functie-standard-v1", "m4-meetbaar-standard-v1"],
  },
};
