import type { AdaptiveModuleDefinition } from "./adaptive-module-definition";

const interventions = {
  "m7-koppelvormen-standard-v1": {
    id: "m7-koppelvormen-standard-v1",
    objectiveId: "sa.m07.koppelvormen",
    speaker: "alexander",
    title: "Drie uitwisselingspatronen, drie verschillende beloften",
    kind: "explanation",
    body: "In deze module onderscheiden we bevragen, gebeurtenisgedreven uitwisseling en bestandsuitwisseling als werkvormen om integratiekeuzes te analyseren. Bij bevragen bepaalt de vrager wanneer informatie nodig is. Bij een gebeurtenis bepaalt de verzender wanneer iets relevants is gebeurd. Bij bestandsuitwisseling wordt informatie gebundeld op een afgesproken moment. De vorm is niet automatisch goed of fout; hij moet passen bij frequentie, tijdigheid, herleidbaarheid en faalgedrag.",
    visualMode: "integration-patterns",
  },
  "m7-belofte-standard-v1": {
    id: "m7-belofte-standard-v1",
    objectiveId: "sa.m07.afhankelijkheid",
    speaker: "alexander",
    title: "Elke koppeling is ook een afspraak",
    kind: "explanation",
    body: "Een koppeling maakt twee partijen afhankelijk van een gedeelde belofte: welke informatie wordt uitgewisseld, wanneer, in welk formaat, met welke betekenis en wat er gebeurt bij uitval. Daardoor is integratie niet alleen techniek. Een wijziging aan één kant kan gevolgen hebben voor de andere partij en vraagt dus beheer van het contract én de relatie.",
    visualMode: "integration-promise",
  },
  "m7-belofte-practice-v1": {
    id: "m7-belofte-practice-v1",
    objectiveId: "sa.m07.afhankelijkheid",
    speaker: "interviewer",
    title: "Welke belofte doe je aan de keuringsinstantie?",
    kind: "practice",
    body: "Middelveen wil de keuringsuitslag automatisch ontvangen. De techniek kan een bericht afleveren, maar daarmee is de integratieafspraak nog niet compleet.",
    prompt: "Welke twee afspraken moeten gemeente en keuringsinstantie minimaal expliciet maken naast het technische transport?",
    visualMode: "integration-promise",
  },
  "m7-failure-standard-v1": {
    id: "m7-failure-standard-v1",
    objectiveId: "sa.m07.koppelvorm-kiezen",
    speaker: "alexander",
    title: "Ontwerp de mislukking mee",
    kind: "explanation",
    body: "Een integratieontwerp is niet af wanneer het happy path werkt. Denk ook aan uitval, dubbel ontvangen, verloren berichten, vertraagde verwerking en onduidelijke bevestiging. Voor Middelveen is juist bij een keuringsuitslag herleidbaarheid belangrijk: kunnen beide partijen aantonen wat is verzonden, ontvangen en verwerkt?",
    visualMode: "failure-path",
  },
  "m7-koppelvorm-practice-v1": {
    id: "m7-koppelvorm-practice-v1",
    objectiveId: "sa.m07.koppelvorm-kiezen",
    speaker: "interviewer",
    title: "Kies op basis van de uitwisseling, niet op voorkeur",
    kind: "practice",
    body: "De keuringsuitslag komt enkele keren per dag, iedere uitslag moet afzonderlijk herleidbaar zijn en de gemeente wil niet continu pollen.",
    prompt: "Welke koppelvorm past het best en welk faalscenario moet je expliciet afdekken?",
    visualMode: "pattern-choice",
  },
  "m7-wendbaarheid-standard-v1": {
    id: "m7-wendbaarheid-standard-v1",
    objectiveId: "sa.m07.wendbaarheid",
    speaker: "alexander",
    title: "Koppelen kost veranderingsvrijheid",
    kind: "explanation",
    body: "Hoe meer een afnemer weet van de interne structuur van een ander systeem, hoe duurder toekomstige wijziging wordt. Een rechtstreekse databasekoppeling lijkt soms snel, maar maakt de afnemer afhankelijk van tabellen, velden en technische keuzes die intern zouden moeten kunnen veranderen. Beoordeel integratie daarom ook op de vraag: wat kunnen beide partijen later nog zelfstandig wijzigen?",
    visualMode: "coupling-impact",
  },
  "m7-landschap-practice-v1": {
    id: "m7-landschap-practice-v1",
    objectiveId: "sa.m07.wendbaarheid",
    speaker: "interviewer",
    title: "Wie merkt deze wijziging?",
    kind: "practice",
    body: "Een bestaande statuskoppeling wordt uitgebreid zodat ook keuringsdetails worden meegestuurd. Dat lijkt hergebruik, maar de belofte van de koppeling verandert.",
    prompt: "Welke bestaande afnemers of beheerafspraken kunnen hierdoor geraakt worden en hoe beoordeel je of hergebruik nog verantwoord is?",
    visualMode: "landscape-impact",
  },
  "m7-techniek-repair-v1": {
    id: "m7-techniek-repair-v1",
    objectiveId: "sa.m07.afhankelijkheid",
    speaker: "interviewer",
    title: "Herstel: een koppeling is niet alleen techniek",
    kind: "repair",
    body: "Een werkende API of berichtenbus zegt nog niets over betekenis, eigenaarschap, wijzigingsafspraken, foutafhandeling of operationele verantwoordelijkheden. Behandel de integratie als een afspraak tussen partijen die technisch wordt gerealiseerd.",
    prompt: "Welke afspraak blijft bestaan als je morgen de onderliggende integratietechniek vervangt?",
    visualMode: "integration-promise",
  },
  "m7-hergebruik-repair-v1": {
    id: "m7-hergebruik-repair-v1",
    objectiveId: "sa.m07.wendbaarheid",
    speaker: "interviewer",
    title: "Herstel: hergebruik is geen doel op zichzelf",
    kind: "repair",
    body: "Een bestaande koppeling hergebruiken is alleen verstandig wanneer de bestaande belofte ook past bij de nieuwe behoefte. Een interface steeds verder oprekken kan bestaande afnemers kwetsbaar maken en de wijzigingsruimte voor iedereen verkleinen.",
    prompt: "Wanneer zou een extra koppeling minder complexiteit veroorzaken dan nog meer hergebruik?",
    visualMode: "landscape-impact",
  },
  "m7-assessment-v1": {
    id: "m7-assessment-v1",
    objectiveId: "sa.m07.koppelvorm-kiezen",
    speaker: "alexander",
    title: "Verplichte eindcheck",
    kind: "assessment",
    body: "De eindcheck controleert of je koppelvormen herkent, afhankelijkheden en faalgedrag meeweegt en de impact van een integratie op de wendbaarheid van het landschap kunt beoordelen.",
    visualMode: "assessment",
  },
} as const;

export const solutionArchitectureModule7: AdaptiveModuleDefinition = {
  courseSlug: "solution-architectuur-ontwerppraktijk",
  sourceModuleId: 7,
  moduleSlug: "integratie-en-applicatielandschap",
  title: "Integratie en applicatielandschap",
  standardReferences: [],
  objectives: [
    "sa.m07.koppelvormen",
    "sa.m07.afhankelijkheid",
    "sa.m07.koppelvorm-kiezen",
    "sa.m07.wendbaarheid",
  ],
  misconceptions: [
    "sa.mc.koppeling-is-alleen-techniek",
    "sa.mc.hergebruik-is-altijd-beter",
  ],
  diagnostics: [
    {
      id: "m7-diag-01",
      objectiveIds: ["sa.m07.koppelvormen"],
      prompt: "Wat onderscheidt gebeurtenisgedreven uitwisseling het duidelijkst van bevragen?",
      kind: "single_choice",
      options: ["Gebeurtenissen zijn altijd sneller", "De verzender bepaalt wanneer relevante informatie wordt aangeboden", "Gebeurtenissen hebben geen foutafhandeling nodig", "De ontvanger bepaalt altijd het moment"],
    },
    {
      id: "m7-diag-02",
      objectiveIds: ["sa.m07.afhankelijkheid"],
      prompt: "Een API-call werkt technisch. Wanneer is de integratieafspraak daarmee compleet?",
      kind: "single_choice",
      options: ["Zodra er HTTP 200 terugkomt", "Pas als ook betekenis, eigenaarschap, wijziging en foutafhandeling zijn afgesproken", "Zodra beide systemen in dezelfde cloud staan", "Zodra monitoring groen is"],
    },
    {
      id: "m7-diag-03",
      objectiveIds: ["sa.m07.koppelvorm-kiezen"],
      prompt: "De keuringsuitslag komt een paar keer per dag en moet per uitslag herleidbaar zijn. Welke richting past het best?",
      kind: "single_choice",
      options: ["Continu bevragen", "Een gebeurtenis per uitslag met bevestiging en logging", "Een willekeurig dagelijks bestand zonder bevestiging", "Rechtstreeks in elkaars database schrijven"],
    },
    {
      id: "m7-diag-04",
      objectiveIds: ["sa.m07.wendbaarheid"],
      prompt: "Waarom is hergebruik van een bestaande koppeling niet automatisch de beste keuze?",
      kind: "single_choice",
      options: ["Hergebruik is altijd beter; bestaande koppelingen moet je daarom altijd oprekken", "Omdat de bestaande koppeling een andere belofte kan hebben en oprekken bestaande afnemers kan raken", "Omdat hergebruik nooit is toegestaan", "Omdat iedere use-case een eigen protocol nodig heeft"],
    },
  ],
  interventions,
  routes: {
    A: [
      "m7-koppelvormen-standard-v1",
      "m7-belofte-standard-v1",
      "m7-belofte-practice-v1",
      "m7-failure-standard-v1",
      "m7-koppelvorm-practice-v1",
      "m7-wendbaarheid-standard-v1",
      "m7-landschap-practice-v1",
      "m7-assessment-v1",
    ],
    B: [
      "m7-belofte-practice-v1",
      "m7-koppelvorm-practice-v1",
      "m7-landschap-practice-v1",
      "m7-assessment-v1",
    ],
    C: [
      "m7-techniek-repair-v1",
      "m7-hergebruik-repair-v1",
      "m7-koppelvorm-practice-v1",
      "m7-landschap-practice-v1",
      "m7-assessment-v1",
    ],
  },
  assessment: [
    {
      id: "m7-assess-01",
      objectiveId: "sa.m07.koppelvormen",
      question: "Wat kenmerkt een gebeurtenisgedreven koppeling ten opzichte van bevragen?",
      options: ["Hij is altijd sneller", "De verzender bepaalt het moment van uitwisseling, niet de ontvanger", "Hij is veiliger", "Hij vergt geen foutafhandeling"],
    },
    {
      id: "m7-assess-02",
      objectiveId: "sa.m07.afhankelijkheid",
      question: "Waarom is elke koppeling een beheerlast?",
      options: ["Koppelingen zijn duur in aanschaf", "Twee partijen zijn voortaan afhankelijk van een afspraak die niemand eenzijdig kan wijzigen", "Ze vragen aparte hardware", "Ze verouderen snel"],
    },
    {
      id: "m7-assess-03",
      objectiveId: "sa.m07.koppelvorm-kiezen",
      question: "De keuringsuitslag komt hooguit een paar keer per dag en moet volledig herleidbaar zijn. Welke koppelvorm past?",
      options: ["Doorlopend bevragen door het zaaksysteem", "Een gebeurtenis per uitslag, met bevestiging en logging", "Een dagelijks bestand", "Handmatige invoer"],
    },
    {
      id: "m7-assess-04",
      objectiveId: "sa.m07.koppelvorm-kiezen",
      question: "Middelveen wil de BRP-gegevens bij elke schermweergave opnieuw ophalen. Wat is het bezwaar?",
      options: ["Het is niet toegestaan", "Het maakt de schermweergave afhankelijk van de beschikbaarheid van de BRP-koppeling", "Het is te traag om te bouwen", "Er is geen bezwaar"],
    },
    {
      id: "m7-assess-05",
      objectiveId: "sa.m07.wendbaarheid",
      question: "Een voorstel koppelt het burgerportaal rechtstreeks aan de database van het zaaksysteem. Wat is het grootste bezwaar?",
      options: ["Het is te snel", "Het portaal wordt afhankelijk van de interne structuur van het zaaksysteem, die niemand meer kan wijzigen", "Het kost meer opslag", "Het is niet in C4 getekend"],
    },
    {
      id: "m7-assess-06",
      objectiveId: "sa.m07.wendbaarheid",
      question: "Wanneer is een extra koppeling wél de betere keuze dan hergebruik van een bestaande?",
      options: ["Altijd, koppelingen zijn goedkoop", "Als de bestaande koppeling een andere belofte doet dan je nodig hebt en oprekken hem voor beide gebruiken onbetrouwbaar maakt", "Nooit", "Als het sneller te bouwen is"],
    },
  ],
  mediaPolicy: { interviewerVideo: false, optionalTutorClipIds: [] },
};
