import type { AdaptiveModuleDefinition } from "./adaptive-module-definition";

const interventions = {
  "m3-stakeholders-standard-v1": {
    id: "m3-stakeholders-standard-v1",
    objectiveId: "sa.m03.stakeholders-identificeren",
    speaker: "alexander",
    title: "Stakeholders zijn meer dan de mensen aan tafel",
    kind: "explanation",
    body: "Een stakeholder is iedereen die de oplossing beïnvloedt, gebruikt, beheert, er risico door loopt of gevolgen ervan ondervindt. Kijk daarom niet alleen naar aanwezige besluitvormers en leveranciers. In Middelveen kan bijvoorbeeld ook een gemachtigde aanvrager geraakt worden, zelfs als die groep niet in de projectkamer vertegenwoordigd is.",
    visualMode: "stakeholder-radar",
  },
  "m3-afwezige-stakeholder-practice-v1": {
    id: "m3-afwezige-stakeholder-practice-v1",
    objectiveId: "sa.m03.stakeholders-identificeren",
    speaker: "interviewer",
    title: "Wie ontbreekt er nog?",
    kind: "practice",
    body: "Aan tafel zitten de opdrachtgever, het klantcontactcentrum, de keuringsinstantie, privacy en IT. Eva vraagt je bewust buiten de deelnemerslijst te kijken.",
    prompt: "Noem één stakeholder die niet aan tafel zit maar wel gevolgen van de oplossing kan ondervinden, en welk belang je van die stakeholder moet onderzoeken.",
    visualMode: "stakeholder-radar",
  },
  "m3-wens-naar-eis-standard-v1": {
    id: "m3-wens-naar-eis-standard-v1",
    objectiveId: "sa.m03.toetsbare-eis",
    speaker: "alexander",
    title: "Een wens wordt pas bruikbaar wanneer je kunt toetsen",
    kind: "explanation",
    body: "'De aanvraag moet snel gaan' geeft richting maar nog geen objectief criterium. Een toetsbare eis maakt duidelijk wat wordt beoordeeld en welke grens voldoende is. Module 4 gaat vervolgens dieper in op kwaliteitsattributen; hier gaat het om de vaardigheid om een stakeholderwens in een controleerbare eis om te zetten.",
    visualMode: "wish-to-requirement",
  },
  "m3-toetsbaar-practice-v1": {
    id: "m3-toetsbaar-practice-v1",
    objectiveId: "sa.m03.toetsbare-eis",
    speaker: "interviewer",
    title: "Maak de wens controleerbaar",
    kind: "practice",
    body: "Een stakeholder zegt: 'De aanvraag moet snel gaan.'",
    prompt: "Schrijf één toetsbare eis. Benoem wat je meet en welke norm voldoende is; voeg waar nodig meetmoment of meetcontext toe.",
    visualMode: "wish-to-requirement",
  },
  "m3-conflict-standard-v1": {
    id: "m3-conflict-standard-v1",
    objectiveId: "sa.m03.belangenconflict",
    speaker: "alexander",
    title: "Botsende belangen zijn informatie, geen fout",
    kind: "explanation",
    body: "Het klantcontactcentrum kan maximale statusinformatie willen om burgers te helpen, terwijl privacy minimale gegevensdeling vraagt. De solution architect probeert zo'n spanning niet stilletjes weg te ontwerpen. Hij maakt duidelijk welke eisen botsen, welke consequenties alternatieven hebben en welke keuze door de bevoegde eigenaar moet worden gemaakt.",
    visualMode: "interest-conflict",
  },
  "m3-conflict-practice-v1": {
    id: "m3-conflict-practice-v1",
    objectiveId: "sa.m03.belangenconflict",
    speaker: "interviewer",
    title: "Maak de patstelling beslisbaar",
    kind: "practice",
    body: "Twee eisen sluiten elkaar uit en beide stakeholders noemen hun eis essentieel.",
    prompt: "Wat lever jij als solution architect aan zodat de bevoegde beslisser de patstelling kan oplossen, zonder zelf de belangenprioriteit te claimen?",
    visualMode: "decision-escalation",
  },
  "m3-architect-kiest-repair-v1": {
    id: "m3-architect-kiest-repair-v1",
    objectiveId: "sa.m03.belangenconflict",
    speaker: "interviewer",
    title: "Herstel: de architect maakt de keuze niet vanzelfsprekend zelf",
    kind: "repair",
    body: "Wanneer twee legitieme stakeholderbelangen elkaar uitsluiten, is het architectuurwerk om consequenties en oplossingsruimte expliciet te maken. De prioriteit tussen businessbelangen hoort bij de bevoegde eigenaar, tenzij jouw mandaat dat expliciet anders regelt.",
    prompt: "Welke informatie moet je aan de beslisser geven zodat de keuze niet op voorkeur maar op consequenties wordt gemaakt?",
    visualMode: "decision-escalation",
  },
  "m3-getal-repair-v1": {
    id: "m3-getal-repair-v1",
    objectiveId: "sa.m03.toetsbare-eis",
    speaker: "interviewer",
    title: "Herstel: een getal alleen maakt een eis nog niet toetsbaar",
    kind: "repair",
    body: "'99,9%' of '10 seconden' klinkt precies, maar zonder te weten wat je meet, wanneer je meet en onder welke omstandigheden kan de norm nog steeds ambigu zijn. Maak het volledige criterium controleerbaar.",
    prompt: "Welke meetcontext ontbreekt vaak bij een eis die alleen een getal noemt?",
    visualMode: "wish-to-requirement",
  },
  "m3-assessment-v1": {
    id: "m3-assessment-v1",
    objectiveId: "sa.m03.toetsbare-eis",
    speaker: "alexander",
    title: "Verplichte eindcheck",
    kind: "assessment",
    body: "De eindcheck controleert of je stakeholders inclusief afwezige groepen kunt herkennen, wensen toetsbaar maakt en botsende belangen correct teruglegt zonder zelf de businessprioriteit te claimen.",
    visualMode: "assessment",
  },
} as const;

export const solutionArchitectureModule3: AdaptiveModuleDefinition = {
  courseSlug: "solution-architectuur-ontwerppraktijk",
  sourceModuleId: 3,
  moduleSlug: "stakeholders-en-eisen",
  title: "Stakeholders en eisen",
  standardReferences: [],
  objectives: [
    "sa.m03.stakeholders-identificeren",
    "sa.m03.toetsbare-eis",
    "sa.m03.belangenconflict",
    "sa.m03.eis-beoordelen",
  ],
  misconceptions: [
    "sa.mc.architect-kiest-bij-botsende-belangen",
    "sa.mc.getal-maakt-eis-toetsbaar",
  ],
  diagnostics: [
    {
      id: "m3-diag-01",
      objectiveIds: ["sa.m03.stakeholders-identificeren"],
      prompt: "Wie is in de Middelveen-casus gemakkelijk over het hoofd te zien als stakeholder?",
      kind: "single_choice",
      options: ["De wethouder", "De leverancier van het zaaksysteem", "De burger die namens een ander een aanvraag indient", "De keuringsinstantie"],
    },
    {
      id: "m3-diag-02",
      objectiveIds: ["sa.m03.toetsbare-eis", "sa.m03.eis-beoordelen"],
      prompt: "Welke formulering maakt 'de aanvraag moet snel gaan' het best toetsbaar?",
      kind: "single_choice",
      options: ["De aanvraag moet zo snel mogelijk gaan", "Een volledige aanvraag levert binnen tien werkdagen een besluit op", "Het portaal moet performant zijn", "De doorlooptijd moet korter dan nu"],
    },
    {
      id: "m3-diag-03",
      objectiveIds: ["sa.m03.belangenconflict"],
      prompt: "Het klantcontactcentrum wil alle statusdetails zien; privacy wil minimale gegevensdeling. Wat is dit?",
      kind: "single_choice",
      options: ["Een misverstand", "Een reëel belangenconflict dat expliciete besluitvorming vraagt", "Alleen een technisch probleem", "Alleen een scopekwestie"],
    },
    {
      id: "m3-diag-04",
      objectiveIds: ["sa.m03.belangenconflict"],
      prompt: "Twee legitieme eisen sluiten elkaar uit en niemand wil wijken. Wat is jouw volgende stap?",
      kind: "single_choice",
      options: ["Zelf de beste eis kiezen", "Beide eisen laten vallen", "Consequenties en opties voorleggen aan degene die de belangen mag prioriteren", "Zelf een compromis vastleggen"],
    },
  ],
  interventions,
  routes: {
    A: [
      "m3-stakeholders-standard-v1",
      "m3-afwezige-stakeholder-practice-v1",
      "m3-wens-naar-eis-standard-v1",
      "m3-toetsbaar-practice-v1",
      "m3-conflict-standard-v1",
      "m3-conflict-practice-v1",
      "m3-assessment-v1",
    ],
    B: [
      "m3-afwezige-stakeholder-practice-v1",
      "m3-toetsbaar-practice-v1",
      "m3-conflict-practice-v1",
      "m3-assessment-v1",
    ],
    C: [
      "m3-architect-kiest-repair-v1",
      "m3-getal-repair-v1",
      "m3-afwezige-stakeholder-practice-v1",
      "m3-conflict-practice-v1",
      "m3-assessment-v1",
    ],
  },
  assessment: [
    {
      id: "m3-assess-01",
      objectiveId: "sa.m03.stakeholders-identificeren",
      question: "Wie is bij Middelveen de meest over het hoofd geziene belanghebbende?",
      options: ["De wethouder", "De leverancier van het zaaksysteem", "De burger die de aanvraag namens een ander indient", "De keuringsinstantie"],
    },
    {
      id: "m3-assess-02",
      objectiveId: "sa.m03.toetsbare-eis",
      question: "Welke formulering zet 'de aanvraag moet snel gaan' het best om naar een toetsbare eis?",
      options: ["De aanvraag moet zo snel mogelijk gaan", "Een volledige aanvraag levert binnen tien werkdagen een besluit op", "Het portaal moet performant zijn", "De doorlooptijd moet korter dan nu"],
    },
    {
      id: "m3-assess-03",
      objectiveId: "sa.m03.eis-beoordelen",
      question: "Wat ontbreekt aan de eis 'het systeem moet betrouwbaar zijn'?",
      options: ["Een verantwoordelijke", "Een norm waaraan je kunt aflezen of eraan voldaan is", "Een prioriteit", "Niets"],
    },
    {
      id: "m3-assess-04",
      objectiveId: "sa.m03.belangenconflict",
      question: "Het klantcontactcentrum wil alle statusdetails zien; de privacyfunctionaris wil minimale gegevensdeling. Wat is dit?",
      options: ["Een misverstand", "Een reëel belangenconflict dat een expliciete beslissing vraagt", "Een technisch probleem", "Een scopekwestie"],
    },
    {
      id: "m3-assess-05",
      objectiveId: "sa.m03.belangenconflict",
      question: "Welk belang van de keuringsinstantie kan botsen met dat van de gemeente?",
      options: ["Beide willen snelheid", "De instantie wil zo min mogelijk koppelingen onderhouden, de gemeente wil geautomatiseerde uitwisseling", "Beide willen lage kosten", "Er botst niets"],
    },
    {
      id: "m3-assess-06",
      objectiveId: "sa.m03.belangenconflict",
      question: "Twee eisen sluiten elkaar uit en niemand wil wijken. Wat doe je?",
      options: ["Zelf kiezen en vastleggen", "Beide eisen laten vallen", "De patstelling met consequenties voorleggen aan wie erover gaat", "Een compromis verzinnen en vastleggen"],
    },
  ],
  mediaPolicy: {
    interviewerVideo: false,
    optionalTutorClipIds: [],
  },
};
