import type { AdaptiveModuleDefinition } from "./adaptive-module-definition";

const interventions = {
  "m5-model-doel-standard-v1": {
    id: "m5-model-doel-standard-v1",
    objectiveId: "sa.m05.modelkeuze",
    speaker: "alexander",
    title: "Eerst de vraag, dan het diagram",
    kind: "explanation",
    body: "Een architectuurmodel is een middel om een vraag te beantwoorden. Begin daarom met stakeholder en beslisvraag. Pas daarna kies je detailniveau, notatie en visualisatie.",
    visualMode: "stakeholder-purpose",
  },
  "m5-c4-standard-v1": {
    id: "m5-c4-standard-v1",
    objectiveId: "sa.m05.c4-niveaus",
    speaker: "alexander",
    title: "Vier C4-niveaus, vier verschillende gesprekken",
    kind: "explanation",
    body: "C4 ordent oplossingsstructuur van System Context via Container en Component naar Code. Het diepste niveau is niet automatisch het beste niveau; het gesprek bepaalt hoeveel detail nodig is.",
    visualMode: "c4-progressive",
  },
  "m5-archimate4-standard-v1": {
    id: "m5-archimate4-standard-v1",
    objectiveId: "sa.m05.archimate4-viewpoint",
    speaker: "alexander",
    title: "ArchiMate 4: model, view en viewpoint",
    kind: "explanation",
    body: "Een rijk architectuurmodel hoeft niet in zijn geheel aan iedere stakeholder te worden getoond. In ArchiMate 4 gebruik je een view als relevante selectie uit het model; een viewpoint beschrijft de conventies en keuzes waarmee zo'n view voor een bepaald doel wordt opgebouwd.",
    visualMode: "archimate4-view",
  },
  "m5-modelmix-standard-v1": {
    id: "m5-modelmix-standard-v1",
    objectiveId: "sa.m05.modelkeuze",
    speaker: "alexander",
    title: "C4 óf ArchiMate 4? Dat is de verkeerde vraag",
    kind: "explanation",
    body: "C4 en ArchiMate 4 lossen niet exact hetzelfde communicatieprobleem op. C4 kan oplossingsstructuur compact tonen; ArchiMate kan de oplossing in bredere architectuurrelaties plaatsen. Gebruik wat het gesprek helpt en combineer waar dat zinvol is.",
    visualMode: "model-purpose-compare",
  },
  "m5-diagramkwaliteit-standard-v1": {
    id: "m5-diagramkwaliteit-standard-v1",
    objectiveId: "sa.m05.diagramkwaliteit",
    speaker: "alexander",
    title: "Een pijl zonder betekenis helpt niemand",
    kind: "explanation",
    body: "Een diagram is niet klaar omdat de symbolen formeel kloppen. Relaties moeten betekenis dragen, het detailniveau moet passen en het beeld moet de vraag beantwoorden waarvoor het gemaakt is.",
    visualMode: "diagram-quality",
  },
  "m5-one-diagram-repair-v1": {
    id: "m5-one-diagram-repair-v1",
    objectiveId: "sa.m05.publiek-detailniveau",
    speaker: "interviewer",
    title: "Eén diagram voor iedereen?",
    kind: "repair",
    body: "Dezelfde onderliggende architectuur kan meerdere views nodig hebben. De vraag is niet hoeveel informatie je kunt tonen, maar welke informatie deze stakeholder nodig heeft.",
    prompt: "Waarom is één allesomvattend diagram meestal juist minder bruikbaar voor verschillende stakeholders?",
    visualMode: "stakeholder-compare",
  },
  "m5-more-detail-repair-v1": {
    id: "m5-more-detail-repair-v1",
    objectiveId: "sa.m05.publiek-detailniveau",
    speaker: "interviewer",
    title: "Meer detail is niet automatisch meer inzicht",
    kind: "repair",
    body: "Detail dat niet helpt bij de vraag maakt een diagram zwaarder en kan de hoofdboodschap verbergen.",
    prompt: "Welke informatie zou je bewust weglaten voor een wethouder, en waarom?",
    visualMode: "detail-filter",
  },
  "m5-notation-repair-v1": {
    id: "m5-notation-repair-v1",
    objectiveId: "sa.m05.diagramkwaliteit",
    speaker: "interviewer",
    title: "Notatiecorrect maar onbruikbaar",
    kind: "repair",
    body: "Formele correctheid is waardevol, maar communicatie faalt alsnog wanneer niet duidelijk is welke vraag of beslissing het diagram ondersteunt.",
    prompt: "Als de notatie klopt maar niemand begrijpt welke beslissing het diagram ondersteunt, wat ontbreekt dan?",
    visualMode: "notation-vs-purpose",
  },
  "m5-view-viewpoint-check-v1": {
    id: "m5-view-viewpoint-check-v1",
    objectiveId: "sa.m05.archimate4-viewpoint",
    speaker: "interviewer",
    title: "View of viewpoint?",
    kind: "check",
    body: "ArchiMate 4 maakt onderscheid tussen het architectuurbeeld dat je daadwerkelijk toont en de conventies waarmee je zo'n beeld voor een bepaald doel opbouwt.",
    prompt: "Beschrijf in je eigen woorden het verschil tussen een view en een viewpoint.",
    visualMode: "archimate4-viewpoint-check",
  },
  "m5-transfer-v1": {
    id: "m5-transfer-v1",
    objectiveId: "sa.m05.modelkeuze",
    speaker: "interviewer",
    title: "Transfer: twee publieken, twee beelden",
    kind: "practice",
    body: "Gebruik dezelfde Middelveen-oplossing, maar ontwerp de communicatie voor twee verschillende publieken.",
    prompt: "Beschrijf één architectuurbeeld voor de wethouder en één voor het integratieteam. Benoem per beeld doel, detailniveau en modelkeuze.",
    visualMode: "stakeholder-transfer",
  },
  "m5-assessment-v1": {
    id: "m5-assessment-v1",
    objectiveId: "sa.m05.diagramkwaliteit",
    speaker: "alexander",
    title: "Verplichte eindcheck",
    kind: "assessment",
    body: "De eindcheck controleert of je model- en detailkeuzes kunt koppelen aan stakeholder en vraag. De beoordeling gebeurt volgens vaste server-side regels.",
    visualMode: "assessment",
  },
} as const;

export const solutionArchitectureModule5: AdaptiveModuleDefinition = {
  courseSlug: "solution-architectuur-ontwerppraktijk",
  sourceModuleId: 5,
  moduleSlug: "modelleren-en-visualiseren",
  title: "Modelleren en visualiseren",
  standardReferences: [
    {
      name: "ArchiMate",
      version: "4",
      reference: "The Open Group C260, April 2026",
    },
    {
      name: "C4 Model",
      version: "current",
      reference: "Context, Container, Component, Code",
    },
  ],
  objectives: [
    "sa.m05.c4-niveaus",
    "sa.m05.publiek-detailniveau",
    "sa.m05.modelkeuze",
    "sa.m05.diagramkwaliteit",
    "sa.m05.archimate4-viewpoint",
  ],
  misconceptions: [
    "sa.mc.een-diagram-voor-iedereen",
    "sa.mc.notatie-is-doel",
    "sa.mc.meer-detail-is-beter",
    "sa.mc.c4-en-archimate-zijn-concurrenten",
    "sa.mc.viewpoint-is-een-plaatje",
  ],
  diagnostics: [
    {
      id: "m5-diag-01",
      objectiveIds: ["sa.m05.c4-niveaus", "sa.m05.publiek-detailniveau"],
      prompt: "Middelveen wil aan de wethouder tonen welke partijen en hoofdsystemen betrokken zijn. Welk C4-niveau helpt dit gesprek het beste?",
      kind: "single_choice",
      options: ["System Context", "Container", "Component", "Code"],
    },
    {
      id: "m5-diag-02",
      objectiveIds: ["sa.m05.modelkeuze"],
      prompt: "De keuringsinstantie wil begrijpen welke systemen communiceren en waar statusuitwisseling plaatsvindt. Welk detailniveau helpt het gesprek het beste?",
      kind: "single_choice",
      options: ["Alle broncode", "Systeem/containerinteracties", "Alleen organisatiedoelen", "Een volledig repositorymodel"],
    },
    {
      id: "m5-diag-03",
      objectiveIds: ["sa.m05.archimate4-viewpoint"],
      prompt: "Je hebt een rijk ArchiMate 4-model, maar de opdrachtgever wil alleen zien hoe de oplossing in het landschap past. Wat doe je?",
      kind: "single_choice",
      options: ["Het hele model tonen", "Een stakeholdergerichte view maken vanuit een passend viewpoint", "Alle elementen naar PDF exporteren", "ArchiMate vermijden en uitsluitend C4 gebruiken"],
    },
    {
      id: "m5-diag-04",
      objectiveIds: ["sa.m05.diagramkwaliteit"],
      prompt: "Een diagram is notatiecorrect maar bevat vijftien systemen en ongelabelde verbindingen. Is het bruikbaar? Leg kort uit waarom.",
      kind: "free_text",
    },
  ],
  interventions,
  routes: {
    A: [
      "m5-model-doel-standard-v1",
      "m5-c4-standard-v1",
      "m5-more-detail-repair-v1",
      "m5-archimate4-standard-v1",
      "m5-modelmix-standard-v1",
      "m5-diagramkwaliteit-standard-v1",
      "m5-transfer-v1",
      "m5-assessment-v1",
    ],
    B: [
      "m5-c4-standard-v1",
      "m5-view-viewpoint-check-v1",
      "m5-modelmix-standard-v1",
      "m5-diagramkwaliteit-standard-v1",
      "m5-transfer-v1",
      "m5-assessment-v1",
    ],
    C: [
      "m5-one-diagram-repair-v1",
      "m5-more-detail-repair-v1",
      "m5-notation-repair-v1",
      "m5-view-viewpoint-check-v1",
      "m5-modelmix-standard-v1",
      "m5-transfer-v1",
      "m5-assessment-v1",
    ],
  },
  assessment: [
    {
      id: "m5-assess-01",
      objectiveId: "sa.m05.c4-niveaus",
      question: "Welke reeks geeft de C4-niveaus van grof naar fijn?",
      options: ["Context, Container, Component, Code", "Container, Context, Code, Component", "Context, Component, Container, Code", "Concept, Context, Component, Code"],
    },
    {
      id: "m5-assess-02",
      objectiveId: "sa.m05.publiek-detailniveau",
      question: "Waarom toon je een wethouder meestal geen technisch container- of componentdetail?",
      options: ["Omdat dat vertrouwelijk is", "Omdat het detailniveau niet aansluit op de vraag en beslissing van die stakeholder", "Omdat C4 alleen voor ontwikkelaars is", "Omdat ArchiMate 4 verplicht is"],
    },
    {
      id: "m5-assess-03",
      objectiveId: "sa.m05.archimate4-viewpoint",
      question: "Wat is in deze module de beste beschrijving van een ArchiMate-view?",
      options: ["Het volledige architectuurrepositorymodel", "Een relevante selectie/presentatie uit het model voor een concrete vraag", "Een lijst met alle toegestane elementen", "Een ander woord voor viewpoint"],
    },
    {
      id: "m5-assess-04",
      objectiveId: "sa.m05.diagramkwaliteit",
      question: "Wanneer is een architectuurdiagram inhoudelijk geslaagd?",
      options: ["Als alle systemen erop staan", "Als de notatie formeel foutloos is", "Als het de vraag voor het bedoelde publiek beantwoordt", "Als het zo veel mogelijk details bevat"],
    },
    {
      id: "m5-assess-05",
      objectiveId: "sa.m05.modelkeuze",
      question: "Hoe moet je C4 en ArchiMate 4 in deze training benaderen?",
      options: ["Als concurrerende standaarden waarvan je er één kiest", "Als verschillende hulpmiddelen die afhankelijk van vraag en context naast elkaar kunnen worden gebruikt", "C4 alleen voor business en ArchiMate alleen voor code", "ArchiMate alleen wanneer C4 tekortschiet"],
    },
  ],
  mediaPolicy: {
    interviewerVideo: false,
    optionalTutorClipIds: ["m5-model-doel-standard-v1", "m5-modelmix-standard-v1"],
  },
};
