import type { AdaptiveModuleDefinition } from "./adaptive-module-definition";

const caseScope = "Gemeente Middelveen wil de vergunningverlening verder digitaliseren. Het beoogde resultaat is digitale indiening, persoonlijke statusinzage en automatische ontvangst van keuringsuitslagen. De opdrachtgever noemt een burgerportaal als gewenste oplossingsrichting. De aanname dat iedere aanvrager de volledige afhandeling digitaal kan volgen is nog niet gevalideerd; de solution architect moet daarom scope en aannames expliciet toetsen zonder de businessvraag over te nemen.";
const caseRequirements = "De dienstverlening wil burgers zo snel mogelijk rijke en actuele statusinformatie tonen. Het beheerteam wil tegelijk voorkomen dat het portaal afhankelijk wordt van interne tabellen of de beschikbaarheid van achterliggende systemen. Eisen zijn onder meer: persoonlijke status mag alleen na betrouwbare identificatie worden getoond; iedere keuringsuitslag moet afzonderlijk herleidbaar zijn met bevestiging en logging; wijzigingen moeten beheersbaar kunnen worden uitgerold.";
const caseModels = "De eindcasus moet voor verschillende stakeholders te beoordelen zijn. Bestuur en proceseigenaren willen vooral de betrokken partijen, verantwoordelijkheden en betekenisvolle relaties begrijpen; het deliveryteam moet daarnaast de technische grenzen en afhankelijkheden van de oplossing kunnen beoordelen. Eén allesomvattend diagram is daarom niet automatisch de beste communicatievorm.";
const caseAlternatives = "Alternatief A laat het burgerportaal rechtstreeks de database van het zaaksysteem lezen en bevraagt brongegevens tijdens schermweergave. De bestaande statuskoppeling wordt uitgebreid met keuringsdetails. Alternatief B gebruikt een gepubliceerde statusinterface tussen portaal en zaaksysteem en ontvangt iedere keuringsuitslag als afzonderlijke gebeurtenis met bevestiging en logging. Voor de vergelijking staat vast dat de dominante spanning bestaat tussen snelle, rijke statusinzage enerzijds en beperkte afhankelijkheid plus beheersbare wijziging anderzijds.";
const casePrinciples = "Voor de opdracht geldt een expliciete principeset: P1 — afnemers gebruiken stabiele gepubliceerde interfaces en zijn niet afhankelijk van interne databasestructuren. P2 — persoonlijke informatie wordt pas getoond nadat de identiteit betrouwbaar is vastgesteld. P3 — migratiestappen zijn zelfstandig bruikbaar en hebben een vooraf bepaald herstelpad. Afwijking van een principe kan alleen met een expliciete context, afweging en consequentie worden verantwoord.";
const caseMigration = "Het voorgestelde veranderpad bevat drie logisch scheidbare delen: digitale indiening terwijl de interne afhandeling nog gelijk blijft; daarna persoonlijke statusinzage met betrouwbare identificatie; daarna de automatische keuringsuitwisseling. Een alternatief voorstel zet alle wijzigingen in één weekend live zonder vooraf afgesproken rollbackcriteria.";

const fullCase = [caseScope, caseRequirements, caseModels, caseAlternatives, casePrinciples, caseMigration].join(" ");

const interventions = {
  "m10-process-full-v1": {
    id: "m10-process-full-v1",
    objectiveId: "sa.m10.scope-aannames",
    speaker: "alexander",
    title: "Werk de eindcasus als één samenhangend ontwerpbesluit uit",
    kind: "check",
    body: "Deze module introduceert geen nieuwe leerstof. Gebruik alleen wat je in Modules 2–9 hebt geoefend. Lees eerst alle casusfeiten, houd feiten en aannames uit elkaar en beoordeel iedere vervolgvraag op de informatie die daar expliciet wordt gegeven. Als je twijfelt over een begrip, ga terug naar de betreffende eerdere module; in de eindcasus krijg je geen inhoudelijke hints.",
    visualMode: "case-process",
  },
  "m10-process-focus-v1": {
    id: "m10-process-focus-v1",
    objectiveId: "sa.m10.scope-aannames",
    speaker: "alexander",
    title: "Gebruik de eerdere modules als referentie, niet als antwoordmachine",
    kind: "repair",
    body: "De diagnose laat een eerder denkpatroon zien dat aandacht verdient. De eindcasus geeft geen vakinhoudelijke oplossing voor. Herlees zo nodig de relevante eerdere module en keer daarna terug. Elke vraag moet op zijn eigen casusfeiten worden beoordeeld; een eerder fout antwoord hoeft een latere vraag dus niet fout te maken.",
    visualMode: "case-process",
  },
  "m10-case-scope-v1": {
    id: "m10-case-scope-v1",
    objectiveId: "sa.m10.scope-aannames",
    speaker: "interviewer",
    title: "Casus A — opdracht, scope en aannames",
    kind: "practice",
    body: caseScope,
    visualMode: "case-scope",
  },
  "m10-case-requirements-v1": {
    id: "m10-case-requirements-v1",
    objectiveId: "sa.m10.kwaliteit-conflict",
    speaker: "interviewer",
    title: "Casus B — stakeholders, eisen en kwaliteit",
    kind: "practice",
    body: caseRequirements,
    visualMode: "case-requirements",
  },
  "m10-case-models-v1": {
    id: "m10-case-models-v1",
    objectiveId: "sa.m10.modelkeuze",
    speaker: "interviewer",
    title: "Casus C — modelleren voor verschillende lezers",
    kind: "practice",
    body: caseModels,
    visualMode: "case-models",
  },
  "m10-case-alternatives-v1": {
    id: "m10-case-alternatives-v1",
    objectiveId: "sa.m10.alternatieven-tradeoff",
    speaker: "interviewer",
    title: "Casus D — alternatieven en trade-offs",
    kind: "practice",
    body: caseAlternatives,
    visualMode: "case-alternatives",
  },
  "m10-case-principles-v1": {
    id: "m10-case-principles-v1",
    objectiveId: "sa.m10.principes-review",
    speaker: "interviewer",
    title: "Casus E — principes en review",
    kind: "practice",
    body: casePrinciples,
    visualMode: "case-principles",
  },
  "m10-case-migration-v1": {
    id: "m10-case-migration-v1",
    objectiveId: "sa.m10.migratierisico",
    speaker: "interviewer",
    title: "Casus F — realisatie en migratie",
    kind: "practice",
    body: caseMigration,
    visualMode: "case-migration",
  },
  "m10-case-complete-v1": {
    id: "m10-case-complete-v1",
    objectiveId: "sa.m10.scope-aannames",
    speaker: "interviewer",
    title: "De integrale casus",
    kind: "practice",
    body: fullCase,
    visualMode: "case-overview",
  },
  "m10-ref-m2-v1": {
    id: "m10-ref-m2-v1",
    objectiveId: "sa.m10.scope-aannames",
    speaker: "alexander",
    title: "Gerichte herhaling — Module 2",
    kind: "repair",
    body: "Herhaal in Module 2 het onderdeel over het toetsen van de ontvangen businessvraag, scope en aannames. Keer daarna terug naar de eindcasus. De inhoudelijke oplossing van deze casus wordt hier niet gegeven.",
  },
  "m10-ref-m34-v1": {
    id: "m10-ref-m34-v1",
    objectiveId: "sa.m10.kwaliteit-conflict",
    speaker: "alexander",
    title: "Gerichte herhaling — Modules 3 en 4",
    kind: "repair",
    body: "Herhaal in Modules 3 en 4 hoe stakeholderbelangen, toetsbare eisen en kwaliteitsattributen worden geanalyseerd. Keer daarna terug naar de eindcasus. De inhoudelijke oplossing wordt hier niet gegeven.",
  },
  "m10-ref-m5-v1": {
    id: "m10-ref-m5-v1",
    objectiveId: "sa.m10.modelkeuze",
    speaker: "alexander",
    title: "Gerichte herhaling — Module 5",
    kind: "repair",
    body: "Herhaal in Module 5 hoe een model of view wordt gekozen voor het informatiebehoefte van de stakeholder. Keer daarna terug naar de eindcasus zonder een model als doel op zichzelf te behandelen.",
  },
  "m10-ref-m67-v1": {
    id: "m10-ref-m67-v1",
    objectiveId: "sa.m10.alternatieven-tradeoff",
    speaker: "alexander",
    title: "Gerichte herhaling — Modules 6 en 7",
    kind: "repair",
    body: "Herhaal in Modules 6 en 7 het vergelijken van alternatieven, expliciete trade-offs, integratieafspraken, faalgedrag en veranderingsafhankelijkheden. Keer daarna terug; de keuze voor de eindcasus wordt hier niet voorgezegd.",
  },
  "m10-ref-m8-v1": {
    id: "m10-ref-m8-v1",
    objectiveId: "sa.m10.principes-review",
    speaker: "alexander",
    title: "Gerichte herhaling — Module 8",
    kind: "repair",
    body: "Herhaal in Module 8 hoe principes worden toegepast, afwijkingen worden gemotiveerd en een ontwerp kritisch wordt gereviewd. Keer daarna terug naar de casus; deze stap geeft geen beoordeling van het voorstel.",
  },
  "m10-ref-m9-v1": {
    id: "m10-ref-m9-v1",
    objectiveId: "sa.m10.migratierisico",
    speaker: "alexander",
    title: "Gerichte herhaling — Module 9",
    kind: "repair",
    body: "Herhaal in Module 9 tussenstappen, volgorde, dubbeldraaien en rollback. Keer daarna terug naar de eindcasus; de migratiekeuze wordt hier niet inhoudelijk ingevuld.",
  },
  "m10-assessment-v1": {
    id: "m10-assessment-v1",
    objectiveId: "sa.m10.migratierisico",
    speaker: "alexander",
    title: "Integrale eindbeoordeling",
    kind: "assessment",
    body: "Beantwoord alle 13 vragen. Elke vraag bevat voldoende informatie om zelfstandig te beoordelen; een fout in een eerdere sectie wordt niet opnieuw als uitgangspunt voor een latere sectie gebruikt.",
    visualMode: "assessment",
  },
} as const;

export const solutionArchitectureModule10: AdaptiveModuleDefinition = {
  courseSlug: "solution-architectuur-ontwerppraktijk",
  sourceModuleId: 10,
  moduleSlug: "integrale-eindcasus",
  title: "Integrale eindcasus",
  standardReferences: [],
  objectives: [
    "sa.m10.scope-aannames",
    "sa.m10.kwaliteit-conflict",
    "sa.m10.modelkeuze",
    "sa.m10.alternatieven-tradeoff",
    "sa.m10.principes-review",
    "sa.m10.migratierisico",
  ],
  misconceptions: [
    "sa.mc.hergebruik-is-altijd-beter",
    "sa.mc.rollback-is-falen",
  ],
  diagnostics: [
    {
      id: "m10-diag-01",
      objectiveIds: ["sa.m10.scope-aannames"],
      prompt: "Een opdracht bevat al een concrete oplossingsrichting. Wat doet de solution architect vóórdat hij die uitwerkt?",
      kind: "single_choice",
      options: ["De businessvraag vervangen door een nieuwe vraag", "De ontvangen opdracht toetsen op scope, aannames en werkbaarheid", "De oplossing direct detailleren", "Alleen de technische haalbaarheid berekenen"],
    },
    {
      id: "m10-diag-02",
      objectiveIds: ["sa.m10.kwaliteit-conflict"],
      prompt: "Twee stakeholders willen tegelijk rijkere actuele statusinformatie en zo weinig mogelijk afhankelijkheid van achterliggende systemen. Wat moet je eerst expliciet maken?",
      kind: "single_choice",
      options: ["Welke stakeholder hiërarchisch het hoogst staat", "Welke kwaliteitsbelangen botsen en welke eisen daaruit volgen", "Welke technologie het nieuwste is", "Welke wens het goedkoopst te bouwen is"],
    },
    {
      id: "m10-diag-03",
      objectiveIds: ["sa.m10.alternatieven-tradeoff", "sa.m10.principes-review"],
      prompt: "Waarom kan een directe koppeling van een portaal met de database van een ander systeem toekomstige verandering bemoeilijken?",
      kind: "single_choice",
      options: ["Omdat een database nooit gekoppeld mag worden", "Omdat het portaal afhankelijk wordt van de interne structuur van dat systeem", "Omdat rechtstreeks hergebruik per definitie de beste keuze is", "Omdat alleen bestandsuitwisseling onderhoudbaar is"],
    },
    {
      id: "m10-diag-04",
      objectiveIds: ["sa.m10.migratierisico"],
      prompt: "Wat betekent een vooraf ontworpen rollbackoptie bij een migratie?",
      kind: "single_choice",
      options: ["Dat het team verwacht dat de migratie mislukt", "Dat criteria en herstelpad vooraf zijn bepaald zodat gecontroleerd kan worden teruggevallen", "Dat oud en nieuw permanent naast elkaar blijven", "Dat livegang niet meer hoeft te worden getest"],
    },
  ],
  interventions,
  routes: {
    A: [
      "m10-process-full-v1",
      "m10-case-scope-v1",
      "m10-case-requirements-v1",
      "m10-case-models-v1",
      "m10-case-alternatives-v1",
      "m10-case-principles-v1",
      "m10-case-migration-v1",
      "m10-assessment-v1",
    ],
    B: ["m10-case-complete-v1", "m10-assessment-v1"],
    C: [
      "m10-process-focus-v1",
      "m10-case-scope-v1",
      "m10-case-requirements-v1",
      "m10-case-models-v1",
      "m10-case-alternatives-v1",
      "m10-case-principles-v1",
      "m10-case-migration-v1",
      "m10-assessment-v1",
    ],
  },
  assessment: [
    {
      id: "m10-assess-01",
      objectiveId: "sa.m10.scope-aannames",
      question: "De opdrachtgever noemt een burgerportaal als gewenste oplossing. Welke analyse hoort bij de solution architect voordat dit als ontwerpbesluit wordt overgenomen?",
      options: ["De businessvraag herschrijven", "Toetsen welk probleem, welke scope en welke aannames met deze oplossingsrichting zijn verbonden", "Alleen een portaalarchitectuur tekenen", "De keuze als gegeven beschouwen omdat de opdrachtgever hem noemt"],
    },
    {
      id: "m10-assess-02",
      objectiveId: "sa.m10.scope-aannames",
      question: "Welke uitspraak uit de casus is expliciet nog een aanname die gevalideerd moet worden?",
      options: ["Iedere aanvrager kan de volledige afhandeling digitaal volgen", "Persoonlijke status vraagt betrouwbare identificatie", "Keuringsuitslagen moeten afzonderlijk herleidbaar zijn", "Er is een beheerteam"],
    },
    {
      id: "m10-assess-03",
      objectiveId: "sa.m10.kwaliteit-conflict",
      question: "Welke combinatie beschrijft de belangrijkste spanning tussen de genoemde stakeholderbelangen?",
      options: ["Meer schermen versus minder schermen", "Rijke actuele statusinzage versus beperkte afhankelijkheid en beheersbare wijziging", "Open source versus closed source", "Projectduur versus aantal teamleden"],
    },
    {
      id: "m10-assess-04",
      objectiveId: "sa.m10.kwaliteit-conflict",
      question: "Welke eis uit de casus is het meest direct toetsbaar als integratie-eis?",
      options: ["De oplossing moet modern zijn", "Iedere keuringsuitslag moet afzonderlijk herleidbaar zijn met bevestiging en logging", "Het portaal moet prettig werken", "De architectuur moet flexibel zijn"],
    },
    {
      id: "m10-assess-05",
      objectiveId: "sa.m10.kwaliteit-conflict",
      question: "Waarom moet de wens voor 'zo snel mogelijk rijke statusinformatie' nog verder worden uitgewerkt voordat hij als toetsbare eis kan dienen?",
      options: ["Omdat alleen technische teams eisen mogen formuleren", "Omdat termen als snel en rijk nog geen expliciete meet- of acceptatiegrens bevatten", "Omdat statusinformatie nooit een eis is", "Omdat stakeholderwensen niet in een ontwerp thuishoren"],
    },
    {
      id: "m10-assess-06",
      objectiveId: "sa.m10.modelkeuze",
      question: "Bestuur wil betekenisvolle relaties en verantwoordelijkheden begrijpen, terwijl het deliveryteam technische grenzen en afhankelijkheden moet beoordelen. Welke modelaanpak past het best?",
      options: ["Eén zo volledig mogelijk diagram voor iedereen", "Alleen een technisch componentdiagram", "Per informatiebehoefte een passende view gebruiken en de views inhoudelijk consistent houden", "Geen modellen gebruiken omdat de stakeholders verschillen"],
    },
    {
      id: "m10-assess-07",
      objectiveId: "sa.m10.alternatieven-tradeoff",
      question: "Voor deze vraag staat vast: de dominante spanning is rijke actuele statusinzage versus beperkte afhankelijkheid en beheersbare wijziging. Welk onderscheid tussen Alternatief A en B is dan architectonisch het meest relevant?",
      options: ["A gebruikt minder bestanden", "A koppelt het portaal aan interne databasestructuur; B gebruikt een gepubliceerde interface en houdt die afhankelijkheid explicieter afgebakend", "B heeft automatisch geen beheerlast", "A is per definitie goedkoper"],
    },
    {
      id: "m10-assess-08",
      objectiveId: "sa.m10.alternatieven-tradeoff",
      question: "Voor deze vraag staat dezelfde dominante spanning expliciet vast. Welke aanvullende afweging hoort bij de keuze voor gebeurtenisgedreven ontvangst van keuringsuitslagen in Alternatief B?",
      options: ["Alleen of de berichtentechniek snel is", "Ook bevestiging, herleidbaarheid, dubbel/verloren ontvangen en operationele foutafhandeling", "Of het portaal dezelfde database gebruikt", "Alleen het aantal berichten per dag"],
    },
    {
      id: "m10-assess-09",
      objectiveId: "sa.m10.alternatieven-tradeoff",
      question: "Voor deze vraag staat opnieuw vast dat veranderbaarheid en beperkte afhankelijkheid zwaar wegen. Welke beslisrationale is het sterkst?",
      options: ["Kies A, want directe databasekoppelingen zijn sneller te bouwen", "Kies B omdat de expliciete interface de interne structuur afschermt, met als consequentie dat het interfacecontract actief beheerd moet worden", "Kies B omdat iedere API altijd beter is", "Kies A omdat hergebruik altijd voorrang heeft"],
    },
    {
      id: "m10-assess-10",
      objectiveId: "sa.m10.principes-review",
      question: "Welk onderdeel van Alternatief A botst het duidelijkst met principe P1: afnemers gebruiken stabiele gepubliceerde interfaces en niet de interne databasestructuur?",
      options: ["Digitale indiening", "Het burgerportaal leest rechtstreeks de database van het zaaksysteem", "Betrouwbare identificatie", "Logging van keuringsuitslagen"],
    },
    {
      id: "m10-assess-11",
      objectiveId: "sa.m10.principes-review",
      question: "Een reviewer motiveert een afwijking van P1 met: 'we doen dit altijd zo en hergebruik is sneller'. Waarom is dit de zwakste onderbouwing?",
      options: ["Omdat principes nooit mogen worden afgeweken", "Omdat context, expliciete afweging en consequenties ontbreken", "Omdat hergebruik verboden is", "Omdat snelheid nooit relevant is"],
    },
    {
      id: "m10-assess-12",
      objectiveId: "sa.m10.migratierisico",
      question: "Welke eerste tussenstap uit de casus levert zelfstandig waarde terwijl de veranderomvang beperkt blijft?",
      options: ["Alle drie de wijzigingen in één weekend", "Digitale indiening live brengen terwijl de interne afhandeling voorlopig gelijk blijft", "Alleen interne tabellen hernoemen", "Eerst alle bestaande integraties vervangen"],
    },
    {
      id: "m10-assess-13",
      objectiveId: "sa.m10.migratierisico",
      question: "Wat is het zwaarste architectonische bezwaar tegen alle wijzigingen in één weekend live zetten zonder vooraf afgesproken rollbackcriteria?",
      options: ["Een weekend is altijd te kort", "Fouten en afhankelijkheden zijn moeilijk te isoleren en er is geen vooraf ontworpen herstelpad wanneer dienstverlening verslechtert", "Er zijn te weinig schermen", "Dubbeldraaien is dan verplicht"],
    },
  ],
  mediaPolicy: { interviewerVideo: false, optionalTutorClipIds: [] },
};
