import type { AdaptiveModuleDefinition } from "./adaptive-module-definition";

const interventions = {
  "m9-tussenstappen-standard-v1": {
    id: "m9-tussenstappen-standard-v1",
    objectiveId: "sa.m09.tussenstappen",
    speaker: "alexander",
    title: "Een eindbeeld is pas bruikbaar met haalbare tussenstappen",
    kind: "explanation",
    body: "Een doelarchitectuur vertelt waar je naartoe wilt, maar niet hoe de organisatie daar veilig en bruikbaar komt. Een goede tussenstap is geen half product: hij vormt een stabiele toestand die zelfstandig waarde levert én de volgende stap mogelijk maakt. Voor Middelveen kan digitale indiening bijvoorbeeld al waarde leveren terwijl de interne afhandeling nog ongewijzigd blijft.",
    visualMode: "migration-states",
  },
  "m9-tussenstap-practice-v1": {
    id: "m9-tussenstap-practice-v1",
    objectiveId: "sa.m09.tussenstappen",
    speaker: "interviewer",
    title: "Wat levert stap 1 al op?",
    kind: "practice",
    body: "Het eindbeeld bevat digitale indiening, statusinzage en geautomatiseerde keuringsuitwisseling. Alles tegelijk opleveren maakt de verandering groot en moeilijk herstelbaar.",
    prompt: "Formuleer één eerste tussenstap die zelfstandig waarde levert zonder dat het volledige eindbeeld al af hoeft te zijn.",
    visualMode: "migration-states",
  },
  "m9-afhankelijkheden-standard-v1": {
    id: "m9-afhankelijkheden-standard-v1",
    objectiveId: "sa.m09.volgorde",
    speaker: "alexander",
    title: "Afhankelijkheden bepalen de volgorde",
    kind: "explanation",
    body: "Een roadmap is meer dan een lijst met wensen. Vraag per stap wat vooraf beschikbaar moet zijn. Statusinzage heeft bijvoorbeeld betrouwbare identificatie nodig voordat je veilig kunt bepalen wiens gegevens getoond worden. Door afhankelijkheden expliciet te maken voorkom je dat teams parallel werk opleveren dat nog niet verantwoord gebruikt kan worden.",
    visualMode: "dependency-sequence",
  },
  "m9-volgorde-practice-v1": {
    id: "m9-volgorde-practice-v1",
    objectiveId: "sa.m09.volgorde",
    speaker: "interviewer",
    title: "Wat moet eerst?",
    kind: "practice",
    body: "Middelveen wil statusinzage voor burgers en een nieuwe identificatievoorziening in dezelfde release.",
    prompt: "Welke afhankelijkheid bepaalt de volgorde en welk risico ontstaat als beide wijzigingen zonder tussenvalidatie tegelijk live gaan?",
    visualMode: "dependency-sequence",
  },
  "m9-dubbeldraaien-standard-v1": {
    id: "m9-dubbeldraaien-standard-v1",
    objectiveId: "sa.m09.risico-beheersen",
    speaker: "alexander",
    title: "Oud en nieuw naast elkaar is een bewuste risicokeuze",
    kind: "explanation",
    body: "Dubbeldraaien kost extra beheer, synchronisatie, support en soms dubbele gegevensverwerking. Toch kan het verstandig zijn wanneer de schade van een mislukte overgang groter is dan die tijdelijke kosten. Beoordeel daarom niet of dubbeldraaien 'mooi' is, maar welk risico het afdekt en hoe lang de parallelle situatie mag bestaan.",
    visualMode: "parallel-run",
  },
  "m9-rollback-standard-v1": {
    id: "m9-rollback-standard-v1",
    objectiveId: "sa.m09.risico-beheersen",
    speaker: "alexander",
    title: "Terugvallen is vooraf ontworpen herstel",
    kind: "explanation",
    body: "Een rollbackoptie betekent niet dat je verwacht te falen. Het betekent dat je vooraf bepaalt onder welke signalen de nieuwe situatie niet veilig genoeg is, hoe je dienstverlening herstelt en welke gegevens of transacties je moet terugzetten of reconciliëren. Zonder terugvaloptie kan één fout de hele dienstverlening blokkeren.",
    visualMode: "rollback-gate",
  },
  "m9-risico-practice-v1": {
    id: "m9-risico-practice-v1",
    objectiveId: "sa.m09.risico-beheersen",
    speaker: "interviewer",
    title: "Wanneer draai je terug?",
    kind: "practice",
    body: "Na livegang blijkt vijf procent van de aanvragen geen bevestiging te krijgen. Het team denkt dit binnen een paar uur te kunnen repareren.",
    prompt: "Welke vooraf afgesproken criteria heb je nodig om rationeel te beslissen of je doorrepareert of terugvalt?",
    visualMode: "rollback-gate",
  },
  "m9-half-product-repair-v1": {
    id: "m9-half-product-repair-v1",
    objectiveId: "sa.m09.tussenstappen",
    speaker: "interviewer",
    title: "Herstel: een tussenstap is geen willekeurig half product",
    kind: "repair",
    body: "Een tussenstap hoort zelfstandig bruikbaar en bestuurbaar te zijn. Alleen 'de helft van de schermen bouwen' is geen architectonische tussenstaat als de organisatie daar nog niets mee kan. Zoek naar een kleinere, afgeronde capability of gebruikssituatie die al waarde levert.",
    prompt: "Hoe herken je dat een tussenstap zelfstandig waarde levert in plaats van alleen technisch half af te zijn?",
    visualMode: "migration-states",
  },
  "m9-rollback-repair-v1": {
    id: "m9-rollback-repair-v1",
    objectiveId: "sa.m09.risico-beheersen",
    speaker: "interviewer",
    title: "Herstel: rollback is geen mislukking",
    kind: "repair",
    body: "Vooraf kunnen terugvallen maakt gecontroleerd veranderen juist mogelijk. De fout is niet dat rollback bestaat, maar dat criteria, gegevensherstel en verantwoordelijkheden pas tijdens een incident bedacht worden.",
    prompt: "Welke voorbereiding maakt terugvallen een beheerste ontwerpkeuze in plaats van paniekreactie?",
    visualMode: "rollback-gate",
  },
  "m9-assessment-v1": {
    id: "m9-assessment-v1",
    objectiveId: "sa.m09.risico-beheersen",
    speaker: "alexander",
    title: "Verplichte eindcheck",
    kind: "assessment",
    body: "De eindcheck controleert of je waardevolle tussenstappen, volgordebepalende afhankelijkheden, parallel draaien en rollback als onderdelen van een beheerste migratie kunt beoordelen.",
    visualMode: "assessment",
  },
} as const;

export const solutionArchitectureModule9: AdaptiveModuleDefinition = {
  courseSlug: "solution-architectuur-ontwerppraktijk",
  sourceModuleId: 9,
  moduleSlug: "realisatie-en-migratie",
  title: "Realisatie en migratie",
  standardReferences: [
    {
      name: "TOGAF® Standard",
      version: "10th Edition",
      reference: "Optionele terminologiereferentie voor Transition Architecture; de leerroute gebruikt primair neutrale termen.",
    },
  ],
  objectives: [
    "sa.m09.tussenstappen",
    "sa.m09.waarde-per-stap",
    "sa.m09.volgorde",
    "sa.m09.risico-beheersen",
  ],
  misconceptions: [
    "sa.mc.tussenstap-is-half-product",
    "sa.mc.rollback-is-falen",
  ],
  diagnostics: [
    {
      id: "m9-diag-01",
      objectiveIds: ["sa.m09.tussenstappen", "sa.m09.waarde-per-stap"],
      prompt: "Wat maakt een tussenstap architectonisch bruikbaar?",
      kind: "single_choice",
      options: ["Dat ongeveer de helft van het eindbeeld gebouwd is", "Dat de stap zelfstandig waarde levert en een stabiele basis voor vervolg vormt", "Dat alle nieuwe technologie al aanwezig is", "Dat hij precies één kwartaal duurt"],
    },
    {
      id: "m9-diag-02",
      objectiveIds: ["sa.m09.volgorde"],
      prompt: "Waarom moet betrouwbare identificatie vóór persoonlijke statusinzage werken?",
      kind: "single_choice",
      options: ["Omdat identificatie sneller te bouwen is", "Omdat je zonder vastgestelde identiteit niet verantwoord kunt bepalen wiens status je toont", "Omdat statusinzage altijd als laatste hoort", "Omdat het goedkoper is"],
    },
    {
      id: "m9-diag-03",
      objectiveIds: ["sa.m09.risico-beheersen"],
      prompt: "Wanneer kan oud en nieuw tijdelijk naast elkaar draaien verstandig zijn?",
      kind: "single_choice",
      options: ["Altijd", "Wanneer de tijdelijke extra kosten lager zijn dan de potentiële schade van een mislukte overgang", "Nooit", "Alleen bij grote systemen"],
    },
    {
      id: "m9-diag-04",
      objectiveIds: ["sa.m09.risico-beheersen"],
      prompt: "Wat betekent een vooraf ontworpen rollbackoptie?",
      kind: "single_choice",
      options: ["Dat het team weinig vertrouwen heeft", "Dat criteria en herstelpad vooraf zijn bepaald zodat een mislukte overgang beheerst kan worden teruggedraaid", "Dat livegang eigenlijk niet mag", "Dat oud en nieuw permanent blijven bestaan"],
    },
  ],
  interventions,
  routes: {
    A: [
      "m9-tussenstappen-standard-v1",
      "m9-tussenstap-practice-v1",
      "m9-afhankelijkheden-standard-v1",
      "m9-volgorde-practice-v1",
      "m9-dubbeldraaien-standard-v1",
      "m9-rollback-standard-v1",
      "m9-risico-practice-v1",
      "m9-assessment-v1",
    ],
    B: [
      "m9-tussenstap-practice-v1",
      "m9-volgorde-practice-v1",
      "m9-risico-practice-v1",
      "m9-assessment-v1",
    ],
    C: [
      "m9-half-product-repair-v1",
      "m9-rollback-repair-v1",
      "m9-volgorde-practice-v1",
      "m9-risico-practice-v1",
      "m9-assessment-v1",
    ],
  },
  assessment: [
    {
      id: "m9-assess-01",
      objectiveId: "sa.m09.tussenstappen",
      question: "Waarom is een einddoelarchitectuur zonder tussenstappen onbruikbaar?",
      options: ["Hij is te abstract", "Er is geen moment waarop de organisatie iets heeft aan het werk dat gedaan is", "Hij is te duur", "Hij verandert te snel"],
    },
    {
      id: "m9-assess-02",
      objectiveId: "sa.m09.waarde-per-stap",
      question: "Wat is een bruikbare eerste stap bij Middelveen?",
      options: ["Alles tegelijk digitaal", "Digitale indiening met ongewijzigde interne afhandeling", "Alleen de keuringskoppeling", "Eerst het zaaksysteem vervangen"],
    },
    {
      id: "m9-assess-03",
      objectiveId: "sa.m09.volgorde",
      question: "Waarom moet de identificatie via DigiD werken vóór de statusinzage?",
      options: ["Het is makkelijker", "Zonder vastgestelde identiteit kun je niet bepalen wiens status je toont", "Het is goedkoper", "Dat hoeft niet"],
    },
    {
      id: "m9-assess-04",
      objectiveId: "sa.m09.volgorde",
      question: "Middelveen wil de keuringskoppeling en het burgerportaal tegelijk opleveren. Welk risico ontstaat?",
      options: ["Hogere kosten", "Bij een storing is niet vast te stellen welke van de twee wijzigingen de oorzaak is", "Meer testwerk", "Geen risico"],
    },
    {
      id: "m9-assess-05",
      objectiveId: "sa.m09.risico-beheersen",
      question: "Een migratieplan zet alle burgers in één weekend over, zonder terugvaloptie. Wat is het bezwaar?",
      options: ["Het weekend is te kort", "Er is geen manier om een fout te herstellen zonder de dienstverlening te staken", "Het is te duur", "Er is geen bezwaar"],
    },
    {
      id: "m9-assess-06",
      objectiveId: "sa.m09.risico-beheersen",
      question: "Wanneer is dubbeldraaien van oud en nieuw de moeite waard?",
      options: ["Altijd", "Als de kosten van dubbeldraaien lager zijn dan de schade van een mislukte overgang", "Nooit", "Alleen bij grote systemen"],
    },
  ],
  mediaPolicy: { interviewerVideo: false, optionalTutorClipIds: [] },
};
