import type { AdaptiveModuleDefinition } from "./adaptive-module-definition";

const interventions = {
  "m2-opdracht-standard-v1": {
    id: "m2-opdracht-standard-v1",
    objectiveId: "sa.m02.werkbare-opdracht",
    speaker: "alexander",
    title: "Een architectuuropdracht is nog geen oplossing",
    kind: "explanation",
    body: "Een werkbare architectuuropdracht maakt minimaal resultaat, scope en randvoorwaarden expliciet en benoemt wat nog openstaat. Als de gekozen oplossing al in de opdracht staat, is een belangrijk deel van het architectuurwerk feitelijk vooraf ingevuld. De solution architect formuleert de businessvraag niet opnieuw; hij toetst de ontvangen vraag op werkbaarheid en onderzoekt wat werkelijk gevraagd wordt voordat hij gaat ontwerpen.",
    visualMode: "assignment-anatomy",
  },
  "m2-vraag-achter-vraag-standard-v1": {
    id: "m2-vraag-achter-vraag-standard-v1",
    objectiveId: "sa.m02.aannames-herkennen",
    speaker: "alexander",
    title: "Digitalisering is vaak het middel, niet het doel",
    kind: "explanation",
    body: "De vraag 'maak de aanvraag volledig digitaal' kan verschillende onderliggende doelen verbergen: minder handmatige verwerking, minder telefoontjes, betere toegankelijkheid of kortere doorlooptijd. Een architect die het middel voor het doel aanneemt, optimaliseert mogelijk de verkeerde uitkomst. Je gebruikt zulke doelen om te toetsen of de ontvangen vraag goed begrepen en compleet is; de businesskeuze zelf blijft bij de bevoegde opdrachtgever of businessarchitectuur.",
    visualMode: "question-behind-question",
  },
  "m2-scope-standard-v1": {
    id: "m2-scope-standard-v1",
    objectiveId: "sa.m02.scope-afbakenen",
    speaker: "alexander",
    title: "Scope betekent in, uit én later",
    kind: "explanation",
    body: "Scope is geen afvalbak voor alles wat je nu niet wilt oplossen. Maak zichtbaar wat binnen de opdracht valt, wat expliciet buiten de opdracht valt en wat later of elders belegd moet worden. Daarmee voorkom je dat een relevant probleem verdwijnt omdat het niet in deze oplossing wordt ontworpen.",
    visualMode: "scope-canvas",
  },
  "m2-scope-practice-v1": {
    id: "m2-scope-practice-v1",
    objectiveId: "sa.m02.scope-afbakenen",
    speaker: "interviewer",
    title: "Wat betekent 'volledig digitaal'?",
    kind: "practice",
    body: "Middelveen vraagt: 'Maak de aanvraag volledig digitaal.' Het is nog niet duidelijk of dit alleen de indiening betreft of ook keuring, besluitvorming, statusinzage en alternatieve kanalen.",
    prompt: "Welke eerste scopevraag stel je en waarom moet die vóór een oplossingskeuze beantwoord worden?",
    visualMode: "scope-canvas",
  },
  "m2-aannames-standard-v1": {
    id: "m2-aannames-standard-v1",
    objectiveId: "sa.m02.aannames-herkennen",
    speaker: "alexander",
    title: "Een impliciete aanname is ongetest ontwerpwerk",
    kind: "explanation",
    body: "Een aanname hoeft niet onjuist te zijn om riskant te zijn. Het probleem is dat niemand hem expliciet toetst. 'De burger volgt de status online' veronderstelt bijvoorbeeld dat statusinformatie bestaat, dat er een digitaal kanaal is en dat de doelgroep dat kanaal kan gebruiken. Leg zulke aannames zichtbaar vast en laat de eigenaar bevestigen of corrigeren.",
    visualMode: "assumption-register",
  },
  "m2-aannames-practice-v1": {
    id: "m2-aannames-practice-v1",
    objectiveId: "sa.m02.aannames-herkennen",
    speaker: "interviewer",
    title: "De burger zonder DigiD",
    kind: "practice",
    body: "De opdracht zegt niets over burgers die het gekozen digitale identificatiemiddel niet kunnen gebruiken.",
    prompt: "Hoe leg je dit vast zonder zelf een businessbeslissing over het alternatieve kanaal te nemen?",
    visualMode: "assumption-register",
  },
  "m2-randvoorwaarde-standard-v1": {
    id: "m2-randvoorwaarde-standard-v1",
    objectiveId: "sa.m02.werkbare-opdracht",
    speaker: "alexander",
    title: "Eis, randvoorwaarde en aanname zijn niet hetzelfde",
    kind: "explanation",
    body: "Een eis beschrijft waaraan de oplossing of dienstverlening moet voldoen. Een randvoorwaarde begrenst de oplossingsruimte, bijvoorbeeld een verplicht te gebruiken voorziening of harde datum. Een aanname is iets waarvan je voorlopig uitgaat maar dat nog bevestigd moet worden. Door die drie te scheiden kun je later zien wat echt vastlag en wat slechts verondersteld was.",
    visualMode: "constraint-requirement",
  },
  "m2-opdrachtgever-repair-v1": {
    id: "m2-opdrachtgever-repair-v1",
    objectiveId: "sa.m02.werkbare-opdracht",
    speaker: "interviewer",
    title: "Herstel: een incomplete vraag is geen reden om te wachten",
    kind: "repair",
    body: "De opdrachtgever hoeft de architectuuropdracht niet volledig in architectuurtaal te formuleren. De solution architect maakt ontbrekende scope, aannames, doelen en randvoorwaarden zichtbaar en legt de open beslissingen terug bij de juiste eigenaar.",
    prompt: "Welke twee soorten ontbrekende informatie zou je actief boven tafel halen vóór je ontwerpt?",
    visualMode: "assignment-anatomy",
  },
  "m2-buiten-scope-repair-v1": {
    id: "m2-buiten-scope-repair-v1",
    objectiveId: "sa.m02.scope-afbakenen",
    speaker: "interviewer",
    title: "Herstel: buiten scope betekent niet verdwenen",
    kind: "repair",
    body: "Een relevant onderwerp kan buiten deze oplossing vallen en toch belangrijk blijven. Leg daarom vast waar het wordt belegd, welke afhankelijkheid het voor jouw oplossing veroorzaakt en wanneer het opnieuw aandacht vraagt.",
    prompt: "Wat moet je vastleggen wanneer een relevant onderwerp terecht buiten jouw oplossingsscope valt?",
    visualMode: "scope-canvas",
  },
  "m2-assessment-v1": {
    id: "m2-assessment-v1",
    objectiveId: "sa.m02.werkbare-opdracht",
    speaker: "alexander",
    title: "Verplichte eindcheck",
    kind: "assessment",
    body: "De eindcheck controleert of je een architectuuropdracht kunt toetsen op resultaat, scope, aannames, randvoorwaarden en ontbrekende informatie zonder al naar een oplossing te springen.",
    visualMode: "assessment",
  },
} as const;

export const solutionArchitectureModule2: AdaptiveModuleDefinition = {
  courseSlug: "solution-architectuur-ontwerppraktijk",
  sourceModuleId: 2,
  moduleSlug: "businessvraag-ontvangen-en-toetsen",
  title: "De businessvraag ontvangen en toetsen",
  standardReferences: [],
  objectives: [
    "sa.m02.werkbare-opdracht",
    "sa.m02.aannames-herkennen",
    "sa.m02.scope-afbakenen",
    "sa.m02.ontbrekende-informatie",
  ],
  misconceptions: [
    "sa.mc.opdrachtgever-formuleert-vraag-volledig",
    "sa.mc.buiten-scope-is-onbelangrijk",
    "sa.mc.oplossing-is-opdracht",
  ],
  diagnostics: [
    {
      id: "m2-diag-01",
      objectiveIds: ["sa.m02.werkbare-opdracht"],
      prompt: "Wat hoort níet thuis als vaststaand onderdeel van een nog te onderzoeken architectuuropdracht?",
      kind: "single_choice",
      options: ["Het te bereiken resultaat", "De scope", "De vooraf gekozen oplossing", "De randvoorwaarden"],
    },
    {
      id: "m2-diag-02",
      objectiveIds: ["sa.m02.scope-afbakenen"],
      prompt: "Middelveen zegt: 'Maak de aanvraag volledig digitaal.' Welke vraag stel je eerst?",
      kind: "single_choice",
      options: ["Welk platform gebruiken we?", "Wat betekent 'volledig' — alleen indiening of ook andere stappen en kanalen?", "Wat is het budget?", "Welke programmeertaal gebruiken we?"],
    },
    {
      id: "m2-diag-03",
      objectiveIds: ["sa.m02.aannames-herkennen", "sa.m02.ontbrekende-informatie"],
      prompt: "De opdracht zegt niets over burgers zonder DigiD. Wat doe je?",
      kind: "single_choice",
      options: ["Aannemen dat iedereen DigiD heeft", "Zelf een alternatief kanaal ontwerpen", "Als openstaand punt vastleggen en terugleggen bij de opdrachtgever", "Buiten scope zetten en vergeten"],
    },
    {
      id: "m2-diag-04",
      objectiveIds: ["sa.m02.aannames-herkennen"],
      prompt: "De opdrachtgever noemt 'minder telefoontjes naar het klantcontactcentrum'. Wat vertelt dat vooral?",
      kind: "single_choice",
      options: ["Niets relevants voor architectuur", "Het onderliggende doel kan werklastvermindering zijn; digitalisering is mogelijk het middel", "Het portaal moet per definitie snel zijn", "De keuringsinstantie moet sneller werken"],
    },
  ],
  interventions,
  routes: {
    A: [
      "m2-opdracht-standard-v1",
      "m2-vraag-achter-vraag-standard-v1",
      "m2-scope-standard-v1",
      "m2-scope-practice-v1",
      "m2-aannames-standard-v1",
      "m2-aannames-practice-v1",
      "m2-randvoorwaarde-standard-v1",
      "m2-assessment-v1",
    ],
    B: [
      "m2-vraag-achter-vraag-standard-v1",
      "m2-scope-practice-v1",
      "m2-aannames-practice-v1",
      "m2-randvoorwaarde-standard-v1",
      "m2-assessment-v1",
    ],
    C: [
      "m2-opdrachtgever-repair-v1",
      "m2-buiten-scope-repair-v1",
      "m2-scope-practice-v1",
      "m2-aannames-practice-v1",
      "m2-assessment-v1",
    ],
  },
  assessment: [
    {
      id: "m2-assess-01",
      objectiveId: "sa.m02.werkbare-opdracht",
      question: "Wat hoort níet in een architectuuropdracht die nog onderzocht moet worden?",
      options: ["Het te bereiken resultaat", "De randvoorwaarden", "De gekozen oplossing", "De scope"],
    },
    {
      id: "m2-assess-02",
      objectiveId: "sa.m02.aannames-herkennen",
      question: "Waarom is een impliciete aanname riskanter dan een expliciete?",
      options: ["Hij is meestal onjuist", "Hij wordt niet getoetst en kan later stilzwijgend onjuist blijken", "Hij kost meer tijd", "Hij kan nooit toetsbaar worden"],
    },
    {
      id: "m2-assess-03",
      objectiveId: "sa.m02.scope-afbakenen",
      question: "'Maak de aanvraag volledig digitaal.' Welke vraag stel je eerst?",
      options: ["Welk platform gebruiken we?", "Wat betekent 'volledig' — ook de keuring, of alleen de indiening?", "Wat is het budget?", "Wanneer moet het live?"],
    },
    {
      id: "m2-assess-04",
      objectiveId: "sa.m02.ontbrekende-informatie",
      question: "Middelveen zegt niets over burgers zonder DigiD. Hoe verwerk je dat?",
      options: ["Aannemen dat iedereen DigiD heeft", "Vastleggen als openstaand punt en teruggeven aan de opdrachtgever", "Zelf een alternatief kanaal ontwerpen", "Buiten scope verklaren en verder niets doen"],
    },
    {
      id: "m2-assess-05",
      objectiveId: "sa.m02.aannames-herkennen",
      question: "Welke impliciete aanname zit in 'de burger volgt de status online'?",
      options: ["Alleen dat de gemeente een portaal heeft", "Alleen dat statusinformatie bestaat", "Dat er statusinformatie en een digitaal kanaal zijn en dat de burger dat kanaal kan gebruiken", "Geen enkele"],
    },
    {
      id: "m2-assess-06",
      objectiveId: "sa.m02.ontbrekende-informatie",
      question: "De opdrachtgever noemt 'minder telefoontjes naar het klantcontactcentrum'. Wat vertelt dat over de vraag?",
      options: ["Niets relevants", "Het echte doel kan werklastvermindering zijn; digitalisering is het middel", "Het portaal moet snel zijn", "De keuring moet sneller"],
    },
  ],
  mediaPolicy: {
    interviewerVideo: false,
    optionalTutorClipIds: [],
  },
};
